# -*- coding: utf-8 -*-
# Переводы, батч 20: сказочные встречи на карте.
T = {
	'Заблудившийся оленёнок': 'The Lost Fawn',
	'Бродячий менестрель': 'The Wandering Minstrel',
	'Пастушка Мила': 'Mila the Shepherdess',
	'Звон колокольчика': 'A Tinkling Bell',
	'Болотные огоньки': "Will-o'-the-Wisps",
	'Черепаха-отшельница': 'The Hermit Tortoise',
	'Гномы-рудокопы': 'The Dwarf Miners',
	'Дракончик-непоседа': 'The Restless Dragonling',
	'У ручья дрожит пятнистый оленёнок: он отбился от матери и боится идти в чащу один.\n\nС опушки неподалёку доносится тревожный зов оленихи.': 'A spotted fawn trembles by the brook: it has lost its mother and is afraid to enter the thicket alone.\n\nFrom a nearby glade comes the anxious call of a doe.',
	'Проводить его к матери (−3 очка хода)': 'Lead it back to its mother (−3 movement points)',
	'Олениха бережно уводит малыша в зелёную тень. Лесные духи шепчут вам вслед добрые слова.': 'The doe gently leads her little one into the green shade. The forest spirits whisper kind words after you.',
	'Указать дорогу и ехать дальше': 'Point the way and ride on',
	'Оленёнок неуверенно семенит к опушке. Вскоре издалека доносится радостный зов — нашёлся!': 'The fawn trots uncertainly toward the glade. Soon a joyful call rings out in the distance — found!',
	'У придорожного камня отдыхает менестрель с потёртой лютней.\n\n«Сэр рыцарь! За скромную плату я сложу балладу о ваших подвигах — её будут петь в каждой таверне королевства!»': "A minstrel with a worn lute rests by a roadside stone.\n\n“Sir knight! For a modest fee I'll compose a ballad of your deeds — it will be sung in every tavern in the kingdom!”",
	'Заказать балладу (150 золота)': 'Commission a ballad (150 gold)',
	'Звонкая баллада разносится по долине. Воины расправляют плечи: им есть чем гордиться!': 'A ringing ballad carries across the valley. Your soldiers square their shoulders — they have much to be proud of!',
	'Спеть с ним у костра': 'Sing with him by the campfire',
	'Вы поёте до первых звёзд. Менестрель обещает вставить в балладу и ваш куплет.': 'You sing until the first stars appear. The minstrel promises to add your verse to the ballad.',
	'Юная пастушка утирает слёзы:\n\n«Моя овечка Белянка убежала к южной чаще! Одна я туда идти боюсь…»': "A young shepherdess wipes away her tears:\n\n“My little sheep Snowdrop ran off toward the southern thicket! I'm too scared to go there alone…”",
	'Я найду Белянку!': "I'll find Snowdrop!",
	'«Спасибо, сэр рыцарь! Белянку легко узнать — у неё на шее колокольчик».': '“Thank you, sir knight! Snowdrop is easy to spot — she has a little bell around her neck.”',
	'Позже, Мила': 'Later, Mila',
	'«Я буду ждать здесь, у дороги».': "“I'll wait right here by the road.”",
	'«Вы ещё не нашли Белянку? Она убежала к южной чаще — прислушайтесь, не звенит ли колокольчик!»': "“Haven't you found Snowdrop yet? She ran toward the southern thicket — listen for her little bell!”",
	'Продолжаю поиски': "I'm still searching",
	'Вы киваете и снова отправляетесь в путь.': 'You nod and set off again.',
	'Из-за кустов доносится тихий звон. Белянка запуталась шерстью в колючем шиповнике и жалобно блеет.': "A soft tinkling comes from behind the bushes. Snowdrop's fleece is tangled in a thorny briar, and she bleats pitifully.",
	'Освободить Белянку и отвести домой': 'Free Snowdrop and lead her home',
	'Вы осторожно распутываете шерсть. Белянка радостно семенит за вашим конём.': 'You carefully untangle her fleece. Snowdrop trots happily after your horse.',
	'Мила бросается обнимать Белянку:\n\n«Вы её нашли! Возьмите, сэр рыцарь, — это всё, что мы с бабушкой накопили. Пусть вам всегда везёт в пути!»': "Mila rushes to hug Snowdrop:\n\n“You found her! Please take this, sir knight — it's all my grandmother and I have saved. May luck be with you on every road!”",
	'Благодарю, Мила': 'Thank you, Mila',
	'Пастушка машет вам вслед, пока отряд не скрывается за поворотом.': 'The shepherdess waves after you until your company disappears around the bend.',
	'Оставь золото себе': 'Keep the gold',
	'Мила краснеет и дарит вам венок из полевых цветов. Такие подвиги тоже делают героев.': 'Mila blushes and gives you a wreath of wildflowers. Deeds like this make heroes too.',
	'Над трясиной пляшут голубые огоньки. Они то подлетают ближе, то зовут за собой вглубь топи — туда, где что-то блестит.': 'Blue lights dance above the bog. They drift closer, then beckon you deeper into the marsh — toward something glittering.',
	'Пойти за огоньками (−4 очка хода)': 'Follow the lights (−4 movement points)',
	'Огоньки приводят к старому сундучку, затянутому ряской. Внутри — позабытые монеты!': 'The lights lead you to an old casket covered in duckweed. Inside are long-forgotten coins!',
	'Полюбоваться ими с тропы': 'Admire them from the path',
	'Мерцание огоньков успокаивает. Вы чувствуете, как к вам возвращаются силы для чар.': 'The flickering lights are soothing. You feel your strength for spells returning.',
	'На замшелом камне греется огромная черепаха. Говорят, она помнит времена, когда болота были цветущим лугом.': 'A huge tortoise basks on a mossy stone. They say she remembers the days when the marshes were a blooming meadow.',
	'Выслушать её рассказ (−3 очка хода)': 'Listen to her tale (−3 movement points)',
	'Черепаха неспешно рассказывает о светлой магии старых друидов. Её мудрость остаётся с вами.': 'The tortoise slowly tells of the bright magic of the old druids. Her wisdom stays with you.',
	'Угостить её свежими водорослями': 'Treat her to fresh water weed',
	'Черепаха благодарно жмурится. Кажется, она улыбается.': 'The tortoise squints gratefully. She seems to be smiling.',
	'Из-под обвала доносится ворчание:\n\n«Эй, наверху! Нас тут камнем привалило, а кирки остались снаружи!»': "Grumbling comes from beneath a rockfall:\n\n“Hey, up there! We're stuck under the stones, and our picks are outside!”",
	'Разобрать завал (−4 очка хода)': 'Clear the rubble (−4 movement points)',
	'Гномы выбираются, отряхивая бороды, и отсыпают вам горсть самоцветов из своей добычи.': 'The dwarves climb out, dusting off their beards, and pour you a handful of gems from their haul.',
	'Оставить им кирки и припасы (100 золота)': 'Leave them picks and supplies (100 gold)',
	'Гномы откапываются сами, а их старейшина дарит вашим воинам наплечники гномьей ковки.': 'The dwarves dig themselves out, and their elder gifts your soldiers pauldrons of dwarven make.',
	'На скале сидит дракончик размером с кошку и безуспешно пытается выдохнуть пламя — получается только дым.': 'A cat-sized dragonling sits on a rock, trying in vain to breathe fire — only smoke comes out.',
	'Поделиться обедом': 'Share your lunch',
	'Дракончик жадно уплетает хлеб с сыром и довольно фыркает искрами.': 'The dragonling gobbles up the bread and cheese and snorts happy sparks.',
	'Подбодрить и поучить терпению (−2 очка хода)': 'Encourage it and teach it patience (−2 movement points)',
	'С третьей попытки у дракончика выходит крошечный огонёк! В благодарность он дарит вам тёплую чешуйку, полную магии.': 'On the third try the dragonling makes a tiny flame! In gratitude it gives you a warm scale full of magic.',
	'Золото: %+d': 'Gold: %+d',
	'Опыт: +%d': 'Experience: +%d',
	'Мана полностью восполнена': 'Mana fully restored',
	'Очки хода: %+d': 'Movement points: %+d',
	'+%d к Атаке': '+%d Attack',
	'+%d к Защите': '+%d Defense',
	'+%d к Силе Магии': '+%d Spell Power',
	'Кажется, в кошельке не хватает золота.': 'It seems your purse is a little too light.',
}
