# -*- coding: utf-8 -*-
# Переводы, батч 3: главы, эпилоги, астрологи, классы, навыки, подвиги, имена.
T = {
"Ваша победоносное войско вступило в туманные трясины Топей Скорби!\n\nДревний Лич осквернил святилища и поднял из болотных могил орды скелетов и зомби. Трясина бурлит темной скверной!\n\n✦ ВАШИ ЦЕЛИ В ГЛАВЕ 2:\n1. Отыщите Хижину Болотной Ведьмы (6, 17) и добудьте Костяной Ключ.\n2. Преодолейте трясину и откройте Костяные Врата (14, 11).\n3. Сокрушите Древнего Лича в Цитадели (28, 11) и очистите Алтарь Друидов (27, 4)!": "Your victorious army has entered the misty quagmires of the Fens of Sorrow!\n\nThe Ancient Lich defiled the shrines and raised hordes of skeletons and zombies from the bog graves. The mire seethes with dark blight!\n\n✦ YOUR GOALS IN CHAPTER 2:\n1. Find the Swamp Witch's Hut (6, 17) and obtain the Bone Key.\n2. Cross the mire and open the Bone Gates (14, 11).\n3. Crush the Ancient Lich at the Citadel (28, 11) and cleanse the Druid Altar (27, 4)!",
"Добро пожаловать в земли Сказочного Леса!\n\nШайки разбойников атаковали Священную Рощу и похитили священный Венец Королевы Фей. Без него древняя магия леса увядает.\n\n✦ ВАШИ ЦЕЛИ В ГЛАВЕ 1:\n1. Очистите долину от банд гоблинов и стай волков.\n2. Навестите Хижину Лесника (7, 18) на юге за Ключом от Врат.\n3. Сразите Атамана в Логове (28, 11) и верните Венец Королеве Фей (27, 4)!": "Welcome to the lands of the Fairy-Tale Forest!\n\nBandit gangs attacked the Sacred Grove and stole the sacred Crown of the Fairy Queen. Without it, the ancient magic of the forest is withering.\n\n✦ YOUR GOALS IN CHAPTER 1:\n1. Rid the valley of goblin gangs and wolf packs.\n2. Visit the Forester's Hut (7, 18) in the south for the Gate Key.\n3. Defeat the Chieftain at the Lair (28, 11) and return the Crown to the Fairy Queen (27, 4)!",
"Атаман разбойников повержен, и вся долина избавлена от зла!\n\nСвященный Венец озаряет ваши доспехи древним золотым светом!\n\nСкорее доставьте Венец Королеве Фей в Священную Рощу на северо-востоке (27, 4)!": "The bandit chieftain is vanquished, and the whole valley is delivered from evil!\n\nThe sacred Crown bathes your armor in ancient golden light!\n\nHurry — bring the Crown to the Fairy Queen in the Sacred Grove in the north-east (27, 4)!",
"📜 АСТРОЛОГИ ОБЪЯВЛЯЮТ... 📜": "📜 THE ASTROLOGERS PROCLAIM... 📜",
"Неделя Фей": "Week of the Fairies",
"Неделя Золота": "Week of Gold",
"Неделя Магии": "Week of Magic",
"Неделя Воинской Доблести": "Week of Martial Valor",
"Астрологи объявляют Неделю Фей!\n\nПрирост лесных лучниц удвоен. 10 фей-лучниц безвозмездно присоединяются к вашей армии!": "The astrologers proclaim the Week of the Fairies!\n\nThe growth of forest archers is doubled. 10 fairy archers join your army free of charge!",
"Астрологи объявляют Неделю Золота!\n\nТорговые пути безопасны, и королевская казна пополняется на +1000 золота!": "The astrologers proclaim the Week of Gold!\n\nThe trade roads are safe, and the royal treasury grows by +1000 gold!",
"Астрологи объявляют Неделю Магии!\n\nЭфирные потоки насыщают разум героя. Запас маны полностью восстановлен, а предел маны увеличен на +20!": "The astrologers proclaim the Week of Magic!\n\nAetherial streams saturate the hero's mind. The mana pool is fully restored and its limit raised by +20!",
"Астрологи объявляют Неделю Воинской Доблести!\n\nВсе отряды королевства вдохновлены боевым духом (+2 к Атаке героя)!": "The astrologers proclaim the Week of Martial Valor!\n\nAll the stacks of the realm are inspired with morale (+2 to the hero's Attack)!",
"🟢 Новобранец (Легко)": "🟢 Recruit (Easy)",
"🟡 Воитель (Нормально)": "🟡 Warrior (Normal)",
"🔴 Герой (Сложно)": "🔴 Hero (Hard)",
"💀 Легенда (Кошмар)": "💀 Legend (Nightmare)",
"Рыцарь Аларик": "Sir Alaric",
"Паладин Королевства": "Paladin of the Kingdom",
"Чародейка Элеонора": "Eleanor the Sorceress",
"Верховный Архимаг": "Archmage Supreme",
"Следопыт Торн": "Thorn the Ranger",
"Хранитель Чащобы": "Warden of the Wildwood",
"Сбалансированный воин.\n\n• Атака: 4  |  Защита: 3\n• Магия: 3  |  Знание: 4\n• Навык: Лидерство (+30% крит)\n• Войско: 6 Грифонов, 18 Фей\n• Предмет: Меч Доблести (+4 Атк)": "A well-balanced warrior.\n\n• Attack: 4  |  Defense: 3\n• Power: 3  |  Knowledge: 4\n• Skill: Leadership (+30% crit)\n• Army: 6 Griffins, 18 Fairies\n• Item: Sword of Valor (+4 Att)",
"Мастер тайной магии.\n\n• Атака: 2  |  Защита: 2\n• Магия: 6  |  Знание: 6 (80 MP)\n• Навык: Волшебство (+25% урон чар)\n• Войско: 4 Грифона, 24 Феи\n• Предмет: Перстень Архимага": "A master of secret magic.\n\n• Attack: 2  |  Defense: 2\n• Power: 6  |  Knowledge: 6 (80 MP)\n• Skill: Sorcery (+25% spell damage)\n• Army: 4 Griffins, 24 Fairies\n• Item: Archmage's Ring",
"Быстрый разведчик лесов.\n\n• Атака: 3  |  Защита: 3\n• Магия: 2  |  Ход: 48 очков\n• Навык: Логистика, Поиск пути\n• Войско: 8 Грифонов, 14 Фей\n• Предмет: Сапоги Странника (+8 MP)": "A swift scout of the woods.\n\n• Attack: 3  |  Defense: 3\n• Power: 2  |  Movement: 48 points\n• Skills: Logistics, Pathfinding\n• Army: 8 Griffins, 14 Fairies\n• Item: Wanderer's Boots (+8 MP)",
"Стрельба": "Archery",
"Нападение": "Offense",
"Логистика": "Logistics",
"Поиск пути": "Pathfinding",
"Лидерство": "Leadership",
"Волшебство": "Sorcery",
"Мистицизм": "Mysticism",
"Увеличивает урон всех стрелков в войске на 20%.": "Increases the damage of all shooters in the army by 20%.",
"Увеличивает урон отрядов в ближнем бою на 15%.": "Increases the melee damage of all stacks by 15%.",
"Увеличивает запас очков хода на +8 каждый день.": "Adds +8 movement points every day.",
"Снижает штраф за бездорожье: трава стоит 1 очко хода вместо 2.": "Reduces the off-road penalty: grass costs 1 movement point instead of 2.",
"Боевой дух: 15% шанс крит. удара (+30% урона) и шанс дополнительного хода при атаке: 5% + 10% за уровень навыка.": "Morale: a 15% chance of a critical strike (+30% damage) and a chance of an extra turn when attacking: 5% + 10% per skill level.",
"Увеличивает урон всех атакующих заклинаний героя на 25%.": "Increases the damage of all the hero's attack spells by 25%.",
"Восстанавливает герою дополнительно +10 маны каждый новый день.": "Restores an extra +10 mana to the hero each new day.",
"Первая победа": "First Blood",
"Одержите первую победу в тактическом бою.": "Win your first tactical battle.",
"Без единой потери": "Without a Single Loss",
"Побеждите в бою, не потеряв ни одного воина.": "Win a battle without losing a single warrior.",
"Возвращение Венца": "Return of the Crown",
"Сокрушите Атамана разбойников.": "Defeat the Bandit Chieftain.",
"Развеянная тьма": "Darkness Dispelled",
"Уничтожьте Древнего Лича.": "Destroy the Ancient Lich.",
"Владыка Огня повержен": "The Fire Lord Felled",
"Победите Красного Дракона.": "Defeat the Red Dragon.",
"Зачарованный Лес спасён": "The Enchanted Forest Saved",
"Завершите первую главу кампании.": "Complete the first chapter of the campaign.",
"Топи очищены": "The Fens Cleansed",
"Завершите вторую главу кампании.": "Complete the second chapter of the campaign.",
"Великая Сказка": "The Great Tale",
"Завершите всю кампанию.": "Complete the entire campaign.",
"Неделя в походе": "A Week on the March",
"Доведите свой поход до седьмого дня.": "Bring your campaign to its seventh day.",
"Богатая казна": "A Wealthy Treasury",
"Соберите 5000 золота.": "Amass 5000 gold.",
"Прославленный герой": "A Renowned Hero",
"Достигните 5 уровня.": "Reach level 5.",
"Грифоны": "Griffins",
"Королевские Грифоны": "Royal Griffins",
"Феи-лучницы": "Fairy Archers",
"Королевские Феи": "Royal Fairies",
"Древни": "Treants",
"Лесные волки": "Forest Wolves",
"Гоблины": "Goblins",
"Скелеты-лучники": "Skeleton Archers",
"Болотные Зомби": "Swamp Zombies",
"Лесные Друиды": "Forest Druids",
"Лич Некромант": "Lich Necromancer",
"Светлые Пегасы": "Radiant Pegasi",
"Каменные Стражи": "Stone Guardians",
"Лисы-Оборотни": "Fox Shifters",
"Меч Доблести": "Sword of Valor",
"Щит Заступника": "Aegis Shield",
"Сапоги Странника": "Wanderer's Boots",
"Перстень Архимага": "Archmage's Ring",
"Панцирь Древнего Стража": "Ancient Warden's Carapace",
"Венец Королевы Фей": "Fairy Queen's Crown",
"Рог Доблести": "Horn of Valor",
"Плащ Странника": "Wanderer's Mantle",
"Оружие": "Weapon",
"Щит": "Shield",
"Доспех": "Armor",
"Обувь": "Boots",
"Кольцо": "Ring",
"Реликвия": "Relic",
"Шлем": "Helm",
}
