# -*- coding: utf-8 -*-
# Переводы, батч 7: бестиарий, торговец, сложность кампании, анимации, двеллинги.
T = {
"📖 Кодекс существ": "📖 Creature Codex",
"📖 КОДЕКС СУЩЕСТВ": "📖 CREATURE CODEX",
"тир": "tier",
"Сложность кампании:": "Campaign difficulty:",
"Упрощённые анимации (для слабых устройств)": "Reduced animations (for slower devices)",
"Бродячий торговец": "The Wandering Merchant",
"🧳 Бродячий торговец": "🧳 The Wandering Merchant",
"«Товары на сегодня распроданы, добрый рыцарь! Загляните на следующей неделе!»": "«Sold out for today, good knight! Come back next week!»",
"До встречи": "Farewell",
"«Торг здесь прост, сэр рыцарь: цены честные, товары редкие!»\n\n": "«My trading is simple, sir knight: honest prices, rare goods!»\n\n",
"%d) %s — артефакт (%d зол.)": "%d) %s — artifact (%d gold)",
"%d) Отряд «%s» ×%d — (%d зол.)": "%d) A stack of %s x%d — (%d gold)",
"Купить: %s (%d зол.)": "Buy: %s (%d gold)",
"Купить: %s ×%d (%d зол.)": "Buy: %s x%d (%d gold)",
"Стрелок": "Shooter",
"Летун": "Flyer",
"Двойной выстрел": "Double Shot",
"Огненное дыхание": "Fire Breath",
"Трупный яд": "Corpse Poison",
"Регенерация +%d": "Regeneration +%d",
"Отражение %d%%": "Reflection %d%%",
"Уклонение %d%%": "Evasion %d%%",
"Колдун": "Caster",
"Пехота ближнего боя": "Melee infantry",
"Роща Волшебных Фей": "The Grove of Magic Fairies",
"Круг Болотных Друидов": "The Circle of Swamp Druids",
"Гнездовье Королевских Грифонов": "The Royal Griffin Roost",
"Хранительница рощи приветствует паладина:\n\n«Мы готовы направить лучниц на службу Королевству!»\n\nДоступно: %d фей-лучниц (по %d золота)\nВ вашей казне: %d золота": "The grove's keeper greets the paladin:\n\n«We are ready to send our archers into the Kingdom's service!»\n\nAvailable: %d fairy archers (at %d gold each)\nYour treasury: %d gold",
"Все феи-лучницы уже наняты на этой неделе!\n\nНовые добровольцы прибудут с началом новой недели (День 8).": "All fairy archers have already been hired this week!\n\nNew volunteers will arrive with the new week (Day 8).",
"Нанять всех доступных (%d фей за %d зол.)": "Hire all available (%d fairies for %d gold)",
"Верховный друид предлагает помощь природы:\n\nДоступно: %d лесных друидов (по %d золота)\nКазна: %d золота": "The Archdruid offers nature's aid:\n\nAvailable: %d forest druids (at %d gold each)\nTreasury: %d gold",
"Все друиды уже присоединились к вашему войску на этой неделе!": "All druids have already joined your army this week!",
"Нанять отряд (%d друидов за %d зол.)": "Hire the stack (%d druids for %d gold)",
"Гордые грифоны готовы взмыть в бой:\n\nДоступно: %d грифонов (по %d золота)\nКазна: %d золота": "Proud griffins are ready to soar into battle:\n\nAvailable: %d griffins (at %d gold each)\nTreasury: %d gold",
"Все грифоны уже наняты на этой неделе!": "All griffins have already been hired this week!",
"Нанять грифонов (%d за %d зол.)": "Hire griffins (%d for %d gold)",
"Недостаточно золота (нужно хотя бы %d зол.)": "Not enough gold (at least %d gold required)",
"🟢 Новобранец (Легко)": "🟢 Recruit (Easy)",
"🟡 Воитель (Нормально)": "🟡 Warrior (Normal)",
"🔴 Герой (Сложно)": "🔴 Hero (Hard)",
"💀 Легенда (Кошмар)": "💀 Legend (Nightmare)",
"Реестр наёмных жилищ: новый наём = новая запись здесь, без правок кода world_map. intro/soldout/hire_btn — шаблоны с %d под [запас, цена, казна].": "",
}
