# -*- coding: utf-8 -*-
# Переводы, батч 4: описания заклинаний/артефактов, карточки, остатки.
T = {
"Обрушивает пылающую сферу на вражеский отряд, нанося 50 ед. урона (+14 за каждую Силу Магии).": "Hurls a blazing sphere at an enemy stack, dealing 50 damage (+14 per point of Spell Power).",
"Восстанавливает 60 ед. здоровья (+16 за каждую Силу Магии) раненым воинам дружественного отряда.": "Restores 60 health (+16 per point of Spell Power) to the wounded warriors of a friendly stack.",
"Наполняет союзный отряд святой силой, гарантируя максимальный урон каждым ударом на 3 раунда.": "Fills an allied stack with holy power, guaranteeing maximum damage with every strike for 3 rounds.",
"Дарует крылья ветров союзному отряду, увеличивая скорость перемещения на +3 гекса.": "Grants the winds' wings to an allied stack, increasing movement speed by +3 hexes.",
"Походное заклинание: рассеивает туман войны на обширной территории вокруг героя (радиус 9)!": "Adventure spell: dispels the fog of war over a wide area around the hero (radius 9)!",
"Походное заклинание: исцеляет раненых в походе и пополняет все отряды армии на +20% воинов!": "Adventure spell: heals those wounded on the march and replenishes every stack by +20% warriors!",
"Призывает с небес ослепительную молнию, наносящую 65 ед. урона (+18 за каждую Силу Магии).": "Summons a dazzling lightning bolt from the heavens, dealing 65 damage (+18 per point of Spell Power).",
"Оковывает врага инеем, уменьшая его скорость на 50% на 3 раунда.": "Binds the enemy in frost, reducing its speed by 50% for 3 rounds.",
"Укрепляет плоть союзного отряда магией земли, даруя +5 к Защите на 3 раунда.": "Hardens an allied stack's flesh with earth magic, granting +5 Defense for 3 rounds.",
"Ослепляет вражеский отряд яркой вспышкой. Отряд не может ходить, пока не получит урон (до 3 раундов).": "Blinds an enemy stack with a brilliant flash. The stack cannot act until it takes damage (up to 3 rounds).",
"Развевает все тёмные чары с союзного отряда (слепота, яд, корни, замедление) и удваивает его боевой дух на 3 раунда.": "Sweeps away all dark curses from an allied stack (blindness, poison, roots, slow) and doubles its morale for 3 rounds.",
"Окружает союзный отряд куполом света, поглощающим 40 ед. урона (+10 за каждую Силу Магии) на 3 раунда.": "Wraps an allied stack in a dome of light that absorbs 40 damage (+10 per point of Spell Power) for 3 rounds.",
"Осеняет союзный отряд печатью правосудия: на 3 раунда каждый ближний атакующий получает 25% урона ответно.": "Seals an allied stack with the seal of justice: for 3 rounds every melee attacker suffers 25% of the damage in return.",
"Клинок из закаленной звездной стали. Прибавляет +4 к Атаке паладина.": "A blade of quenched star-steel. Adds +4 to the paladin's Attack.",
"Массивный геральдический щит с грифоном. Прибавляет +4 к Защите войска.": "A massive heraldic shield bearing a griffin. Adds +4 to the army's Defense.",
"Сапоги из мягкой эльфийской кожи. Даруют +8 очков хода герою каждый новый день.": "Boots of soft elven leather. Grant the hero +8 movement points each new day.",
"Сапфировое кольцо с древними рунами. Дарует +2 к Силе Магии, +2 к Знанию и +20 к макс. мане.": "A sapphire ring etched with ancient runes. Grants +2 Spell Power, +2 Knowledge and +20 max mana.",
"Пластинчатые латы, выкованные мастерами холмов. +1 к Атаке, +3 к Защите.": "Plate armor forged by the masters of the hills. +1 Attack, +3 Defense.",
"Легендарная реликвия волшебного леса. Дарует +2 ко всем параметрам и +4 очка хода!": "A legendary relic of the enchanted forest. Grants +2 to every stat and +4 movement points!",
"Боевой рог королевских герольдов. Всё войско начинает каждый бой на +2 инициативы быстрее!": "The war horn of the royal heralds. Your entire army begins every battle at +2 initiative!",
"Плащ из туманной пряжи странников: воины в ближнем бою 15% шансом вдвое уменьшают получаемый урон.": "A cloak woven from wanderers' mist: in melee, warriors have a 15% chance to halve the damage they take.",
"%s %s (%s уровень)\n%s": "%s %s (%s level)\n%s",
"%s (%s)\nЧисленность: %d воинов\nЗдоровье верхнего воина: %d / %d HP\nВсего здоровья отряда: %d HP\n\nАтака: %d | Защита: %d\nУрон: %d-%d\nСкорость: %d | Инициатива: %d\n\nОсобенности: %s\nАктивные эффекты: %s": "%s (%s)\nCount: %d warriors\nTop warrior's health: %d / %d HP\nTotal stack health: %d HP\n\nAttack: %d | Defense: %d\nDamage: %d-%d\nSpeed: %d | Initiative: %d\n\nTraits: %s\nActive effects: %s",
"%s\n%s\n\n(Клик — надеть на героя)": "%s\n%s\n\n(Click to equip on the hero)",
"【%s】 %s\n%s\n\n(Клик — снять в рюкзак)": "【%s】 %s\n%s\n\n(Click to remove to satchel)",
"Слот: %s (Свободен)\nВыберите артефакт в рюкзаке ниже": "Slot: %s (Empty)\nChoose an artifact from the satchel below",
"• Нет сюжетных реликвий": "• No story relics",
"• Рюкзак пуст (ищите реликвии на карте)": "• The satchel is empty (look for relics on the map)",
"📜 Знание: %d (%d маны)": "📜 Knowledge: %d (%d mana)",
"🔮 Сила Магии: %d%s": "🔮 Spell Power: %d%s",
"Болотная ведунья мешает зелье в котле:\n\n«Приветствую, сэр Аларик! Древний Лич восстал из затонувших склепов и погрузил край в вечный туман. Он запер вход в свою Цитадель Костяными Вратами, а ключ от них я одна могу сотворить.\n\nПринесите мне три мухомора и жабу... шучу! Вот готовый Костяной Ключ. Идите и сокрушите нечисть!»": "The swamp witch stirs a brew in her cauldron:\n\n«Welcome, Sir Alaric! The Ancient Lich rose from the sunken crypts and drowned the land in eternal fog. He sealed his Citadel with the Bone Gates, and I alone can craft their key.\n\nBring me three fly agarics and a toad... just teasing! Here is the finished Bone Key. Go and smite the undead!»",
"Древний Древень пробудился от векового сна и преграждает путь к тайнику в чащобе!\nРазведка доносит: [Стражи (3 древня, 8 лис-оборотней)].\nЛес защищает свои тайны!": "An Ancient Treant has woken from its age-long sleep and bars the way to a cache deep in the thicket!\nScouts report: [Wardens (3 treants, 8 fox shifters)].\nThe forest guards its secrets!",
"На замшелом камне высечены древние указатели:\n\n← На юг: Хижина Старого Лесника\n↑ На север: Водяная Мельница и Святилище Маны\n→ На восток: Железные Врата и Долина Разбойников": "Ancient signposts are carved into the mossy stone:\n\n← South: the Old Forester's Hut\n↑ North: the Watermill and the Mana Shrine\n→ East: the Iron Gates and the Bandit Valley",
"Герой: %s (%s)": "Hero: %s (%s)",
"Опыт: %d / %d": "Experience: %d / %d",
"Уровень: %d (Глава %d)": "Level: %d (Chapter %d)",
"Увеличить масштаб": "Zoom in",
"Уменьшить масштаб": "Zoom out",
"Сундук пуст, но в золе теплятся угли древнего костра. Приходите на следующей неделе!": "",
"⚔ Перевал открыт": "⚔ The pass is open",
"Продолжить осмотр": "Keep looking",
}
