# -*- coding: utf-8 -*-
# Переводы, батч 23: новые сказочные встречи второй и третьей глав.
T = {
	'Лягушка в короне': 'The Crowned Frog',
	'На широкой кувшинке сидит лягушка в крошечной золотой короне.\n\n«Сэр рыцарь, болотный туман утащил мою жемчужину на дно! Без неё меня не узнают дома, во дворце у Тихой заводи».': 'A frog in a tiny golden crown sits on a broad lily pad.\n\n“Sir knight, the marsh mist dragged my pearl to the bottom! Without it no one at home will know me, in the palace by the Quiet Backwater.”',
	'Нырнуть за жемчужиной (−3 очка хода)': 'Dive for the pearl (−3 movement points)',
	'Жемчужина нашлась под корягой. Лягушка касается короной ваших щитов — и они крепнут, словно заговорённые.': 'The pearl turns up under a snag. The frog touches your shields with her crown, and they grow strong as if enchanted.',
	'Подарить ей блестящую пуговицу': 'Give her a shiny button',
	'Лягушка довольно квакает: пуговица сияет почти как жемчуг. «Во дворце решат, что это новая мода!»': 'The frog croaks happily: the button shines almost like a pearl. “At the palace they will think it is the new fashion!”',
	'Старый паромщик': 'The Old Ferryman',
	'У заросшей протоки дремлет на плоту старик с длинным шестом.\n\n«Посуху через топь не пройти, сэр рыцарь. А я знаю тихие протоки — довезу, куда скажете».': 'An old man with a long pole dozes on a raft by an overgrown channel.\n\n“You cannot cross the marsh on foot, sir knight. But I know the quiet channels — I will take you wherever you say.”',
	'Заплатить за переправу (100 золота)': 'Pay for the crossing (100 gold)',
	'Плот неслышно скользит меж камышей, и отряд выигрывает полдня пути.': 'The raft glides silently through the reeds, and your army saves half a day of travel.',
	'Помочь залатать плот (−2 очка хода)': 'Help patch the raft (−2 movement points)',
	'Вы вместе конопатите щели мхом. Паромщик рассказывает все болотные тропки, какие знает.': 'Together you caulk the cracks with moss. The ferryman tells you every marsh path he knows.',
	'Горячий источник': 'The Hot Spring',
	'Меж тёплых камней бьёт источник, над водой клубится пар. Говорят, здесь отдыхали ещё первые рыцари королевства.': 'A spring bubbles up between warm stones, steam curling over the water. They say the first knights of the kingdom rested here.',
	'Отдохнуть у источника (−3 очка хода)': 'Rest by the spring (−3 movement points)',
	'Тёплая вода смывает усталость дороги. Вы поднимаетесь бодрым, и магия снова звенит в пальцах.': 'The warm water washes away the weariness of the road. You rise refreshed, and magic tingles in your fingers again.',
	'Бросить в источник золотой на удачу (150 золота)': 'Toss a gold coin into the spring for luck (150 gold)',
	'Монета исчезает в клубах пара, и на миг в тумане проступает светлая руна мудрости.': 'The coin vanishes into the steam, and for a moment a bright rune of wisdom appears in the mist.',
	'Гном-кузнец Борин': 'Borin the Dwarf Smith',
	'У остывшего горна вздыхает седобородый гном.\n\n«Беда, сэр рыцарь! Дракон чихнул на весь перевал, и мой молот укатился за Огненные врата. Без него кузня стынет…»': 'A grey-bearded dwarf sighs by his cold forge.\n\n“Trouble, sir knight! The dragon sneezed over the whole pass, and my hammer rolled away beyond the Fire Gate. Without it my forge is going cold…”',
	'Я верну ваш молот!': 'I will bring your hammer back!',
	'«Вот спасибо! Молот тяжёлый, с рунами на рукояти — ни с чем не спутаете».': '“Thank you kindly! It is a heavy hammer with runes on the handle — you cannot mistake it.”',
	'Позже, Борин': 'Later, Borin',
	'«Подожду. Без молота горн всё равно не разжечь».': '“I will wait. The forge will not light without my hammer anyway.”',
	'«Не нашли ещё? Он укатился за Огненные врата, к лавовым ручьям. Руны на рукояти светятся — издалека видно!»': '“Not found it yet? It rolled beyond the Fire Gate, toward the lava streams. The runes on the handle glow — you can see them from afar!”',
	'Борин машет вам вслед рукавицей.': 'Borin waves his mitten after you.',
	'Молот с рунами': 'The Rune Hammer',
	'Среди остывших камней светится руна: из щели торчит рукоять тяжёлого гномьего молота.': 'A rune glows among the cooled stones: the handle of a heavy dwarven hammer sticks out of a crack.',
	'Вытащить молот и вернуть кузнецу': 'Pull out the hammer and return it to the smith',
	'Молот поддаётся не сразу, но вы справляетесь. Теперь скорее к Борину!': 'The hammer does not give way at once, but you manage. Now hurry back to Borin!',
	'Борин прижимает молот к груди, и горн тут же вспыхивает жаром.\n\n«Ну, сэр рыцарь, теперь моя очередь помочь!»': 'Borin hugs the hammer to his chest, and the forge blazes with heat at once.\n\n“Well, sir knight, now it is my turn to help!”',
	'Перековать клинки отряда': "Reforge your army's blades",
	'Молот звенит до самой ночи. Клинки ваших воинов становятся острее гномьей бритвы.': "The hammer rings until nightfall. Your soldiers' blades grow sharper than a dwarf's razor.",
	'Взять гномьим золотом': 'Take it in dwarven gold',
	'Борин отсчитывает монеты с довольным кряхтением: «Честная плата за честную службу!»': 'Borin counts out the coins with a satisfied grunt: “Honest pay for honest service!”',
}
