# -*- coding: utf-8 -*-
# Переводы, батч 12: главное меню, музыкальная шкатулка, подписи карты и сцен,
# которые раньше не попадали в CSV (extract_strings сканировал только 2 файла).
T = {
	# --- Главное меню (main.gd, main.tscn) ---
	"СКАЗКИ КОРОЛЕВСТВА": "KINGDOM TALES",
	"Ламповое тактическое приключение": "A cozy tactical adventure",
	"📜 Продолжить поход": "📜 Continue the journey",
	"📜 Продолжить поход  [%s • Гл. %d, День %d • Ур. %d]": "📜 Continue the journey  [%s • Ch. %d, Day %d • Lvl %d]",
	"Герой": "Hero",
	"⚔️ Новое приключение": "⚔️ New adventure",
	"🛡️ Тактическая арена (Бой)": "🛡️ Tactical Arena (Battle)",
	"🗺️ Выбор Главы (Кампания)": "🗺️ Choose Chapter (Campaign)",
	"🎵 Музыкальная шкатулка": "🎵 Music box",
	"🎼 Музыка (40 тем)": "🎼 Music (40 themes)",
	"ℹ️ Об игре": "ℹ️ About",
	"🚪 Выход": "🚪 Exit",
	"⚙️ НАСТРОЙКИ": "⚙️ SETTINGS",
	"Назад": "Back",
	"Отмена": "Cancel",
	"ВЫБЕРИТЕ КЛАСС ГЕРОЯ": "CHOOSE YOUR HERO'S CLASS",
	"Определите путь и специализацию вашего полководца:": "Choose the path and specialty of your commander:",
	"СЮЖЕТНАЯ КАМПАНИЯ": "STORY CAMPAIGN",
	"Выберите главу для начала сказочного похода:": "Choose a chapter to begin your fairy-tale journey:",
	"🌲 Глава 1: Похищенный Венец (Зачарованный Лес)": "🌲 Chapter 1: The Stolen Crown (The Enchanted Forest)",
	"💀 Глава 2: Проклятые Топи (Древний Лич и Склепы)": "💀 Chapter 2: The Cursed Fens (The Ancient Lich and the Crypts)",
	"🔥 Глава 3: Пик Дракона (Огненный Владыка)": "🔥 Chapter 3: Dragon Peak (The Fire Lord)",
	"О ПРОЕКТЕ": "ABOUT THE PROJECT",
	"«Сказки Королевства» — ламповая сказочная RPG, вдохновленная классикой Heroes of Might and Magic 3 и King's Bounty («Легенда о рыцаре»).\n\nОсобенности игры:\n• Никаких скучных замков и рутины строительства!\n• Уютные сказочные персонажи, водяные мельницы и сундуки с сокровищами.\n• Тактические пошаговые бои на гексах с живой книгой магии героя.\n• 40 уникальных музыкальных тем (клавесин HoMM2 и оркестровая классика).\n• Полная поддержка мобильного управления и сенсорных экранов!":
		"«Kingdom Tales» is a cozy fairy-tale RPG inspired by the classics Heroes of Might and Magic 3 and King's Bounty: The Legend.\n\nFeatures:\n• No dull castles and no building chores!\n• Cozy fairy-tale characters, watermills and treasure chests.\n• Turn-based tactical battles on hexes with the hero's living spellbook.\n• 40 unique music themes (HoMM2 harpsichord and orchestral classics).\n• Full support for mobile controls and touch screens!",

	# --- Тактическая арена (main.gd) ---
	"⚔️ ТАКТИЧЕСКИЙ БОЙ (ДЕМОНСТРАЦИОННАЯ АРЕНА)": "⚔️ TACTICAL BATTLE (DEMONSTRATION ARENA)",
	"Выберите уровень сложности и настройте составы противоборствующих армий:": "Choose a difficulty level and set up the opposing armies:",
	"Сложность:": "Difficulty:",
	"🛡️ ВАШЕ ВОЙСКО": "🛡️ YOUR ARMY",
	"⚔️ ВРАЖЕСКОЕ ВОЙСКО": "⚔️ ENEMY ARMY",
	"🛡️ Сбалансированный": "🛡️ Balanced",
	"🏹 Стрелковый полк": "🏹 Archer Regiment",
	"🦅 Небесный полк (Грифоны)": "🦅 Sky Regiment (Griffins)",
	"🧙 Круг Друидов": "🧙 Druid Circle",
	"🎲 Случайный состав": "🎲 Random lineup",
	"🎲 Перемешать": "🎲 Shuffle",
	"🌲 Лесные разбойники": "🌲 Forest Bandits",
	"💀 Болотная нежить": "💀 Swamp Undead",
	"🔥 Огненные стражи (Дракон)": "🔥 Fire Guardians (Dragon)",
	"⚔️ Мятежная гвардия": "⚔️ The Rebel Guard",
	"🎲 Случайный противник": "🎲 Random opponent",
	"🎲 Другой враг": "🎲 Another foe",
	"%s: %d воинов": "%s: %d warriors",
	"⚔️ В БОЙ НА АРЕНУ!": "⚔️ TO THE ARENA!",

	# --- Музыкальная шкатулка (main.gd) ---
	"🎼 МУЗЫКАЛЬНАЯ ШКАТУЛКА (40 ТЕМ)": "🎼 MUSIC BOX (40 THEMES)",
	"20 тем в стиле Heroes of Might & Magic II (клавесин) + 20 симфонических тем:": "20 themes in the style of Heroes of Might & Magic II (harpsichord) + 20 symphonic themes:",
	"── 🏰 ТЕМЫ В СТИЛЕ HEROES OF MIGHT & MAGIC II (КЛАВЕСИН И РЕНЕССАНС) ──": "── 🏰 HEROES OF MIGHT & MAGIC II STYLE THEMES (HARPSICHORD AND RENAISSANCE) ──",
	"── 🎻 СИМФОНИЧЕСКИЕ И СКАЗОЧНЫЕ ТЕМЫ (HMM3 & ОРКЕСТР) ──": "── 🎻 SYMPHONIC AND FAIRY-TALE THEMES (HMM3 & ORCHESTRA) ──",
	"▶ Играть": "▶ Play",
	"★ Сделать основной": "★ Set as main theme",
	"01. Сад Волшебницы (HoMM2)": "01. The Sorceress's Garden (HoMM2)",
	"02. Замок Рыцаря (HoMM2)": "02. The Knight's Castle (HoMM2)",
	"03. Башня Чернокнижника (HoMM2)": "03. The Warlock's Tower (HoMM2)",
	"04. Академия Магов (HoMM2)": "04. The Wizards' Academy (HoMM2)",
	"05. Придворный Гавот (HoMM2)": "05. Court Gavotte (HoMM2)",
	"06. Сказочный Менуэт (HoMM2)": "06. Fairy-Tale Minuet (HoMM2)",
	"07. Зачарованный Фонтан (HoMM2)": "07. The Enchanted Fountain (HoMM2)",
	"08. Двухголосная Инвенция (HoMM2)": "08. Two-Part Invention (HoMM2)",
	"09. Шут при Дворе — Жига (HoMM2)": "09. The Court Jester — Gigue (HoMM2)",
	"10. Павана Принцессы (HoMM2)": "10. The Princess's Pavane (HoMM2)",
	"11. Лаборатория Алхимика (HoMM2)": "11. The Alchemist's Laboratory (HoMM2)",
	"12. Священная Роща Друидов (HoMM2)": "12. The Druids' Sacred Grove (HoMM2)",
	"13. Серенада Трубадура (HoMM2)": "13. The Troubadour's Serenade (HoMM2)",
	"14. Волшебная Шкатулка (HoMM2)": "14. The Magic Music Box (HoMM2)",
	"15. Королевский Чембало-Марш (HoMM2)": "15. Royal Cembalo March (HoMM2)",
	"16. Пасторальный Рассвет (HoMM2)": "16. Pastoral Dawn (HoMM2)",
	"17. Клавирная Фугетта (HoMM2)": "17. Clavier Fughetta (HoMM2)",
	"18. Хрустальный Спинет (HoMM2)": "18. The Crystal Spinet (HoMM2)",
	"19. Шатёр Лесных Лучников (HoMM2)": "19. The Forest Archers' Pavilion (HoMM2)",
	"20. Фантазия Верховного Мага (HoMM2)": "20. The Archmage's Fantasia (HoMM2)",
	"21. Зачарованный Лес": "21. The Enchanted Forest",
	"22. Королевский Марш": "22. Royal March",
	"23. Уютная Таверна": "23. The Cozy Tavern",
	"24. Тайное Святилище": "24. The Hidden Sanctuary",
	"25. Баллада Странника": "25. The Wanderer's Ballad",
	"26. Рыцарская Честь": "26. A Knight's Honor",
	"27. Хрустальный Источник": "27. The Crystal Spring",
	"28. Ностальгия Героев": "28. Heroes' Nostalgia",
	"29. Древние Руины": "29. Ancient Ruins",
	"30. Утренний Луг": "30. Morning Meadow",
	"31. Кельтский Праздник": "31. Celtic Festival",
	"32. Туманные Топи": "32. The Misty Fens",
	"33. Триумф Королевства": "33. The Kingdom's Triumph",
	"34. Лунная Роща": "34. Moonlit Grove",
	"35. Зов Битвы": "35. Call to Battle",
	"36. Колыбельная Фей": "36. Fairy Lullaby",
	"37. Пик Дракона": "37. Dragon Peak",
	"38. Песнь Менестреля": "38. The Minstrel's Song",
	"39. Храм Света": "39. Temple of Light",
	"40. Великая Сказка": "40. The Grand Tale",
	"Виртуозный клавесин, пасторальная флейта, хрустальные колокольчики": "Virtuoso harpsichord, pastoral flute, crystal bells",
	"Благородный контрапункт на клавесине, лютня и королевские фанфары": "Noble harpsichord counterpoint, lute and royal fanfares",
	"Нисходящие минорные пассажи клавесина, пиццикато и полночный перезвон": "Descending minor harpsichord runs, pizzicato and a midnight chime",
	"Барочная пассакалья 3/4 на клавесине и волшебная челеста": "A baroque passacaglia in 3/4 on harpsichord with a magical celesta",
	"Игривый стаккато-танец клавесина и флейтовый дуэт": "A playful staccato harpsichord dance and a flute duet",
	"Изящный 3/4 менуэт с мордентами клавесина и щипковой лютней": "A graceful 3/4 minuet with harpsichord mordents and a plucked lute",
	"Искрящиеся шестнадцатые переборы клавесина, словно струи воды": "Sparkling harpsichord sixteenths, like streams of water",
	"Классический баховский полифонический диалог двух голосов": "A classic Bach-style polyphonic dialogue of two voices",
	"Задорный галоп 6/8, прыгающий клавесин и средневековая лютня": "A lively 6/8 gallop, a bouncing harpsichord and a medieval lute",
	"Величавая ренессансная поступь, нежный клавесин и басовая лютня": "A stately Renaissance stride, a gentle harpsichord and a bass lute",
	"Хроматические барочные фигуры, стеклянные колокольчики и орган": "Chromatic baroque figures, glass bells and organ",
	"Дорийский напев лесной флейты над струящимися аккордами клавесина": "A Dorian forest-flute tune over flowing harpsichord chords",
	"Романтичный клавесин и мягкая щипковая виуэла менестреля": "A romantic harpsichord and a minstrel's soft plucked vihuela",
	"Звонкий высокий спинет и сказочные колокольчики фей": "A bright high spinet and fairy-tale bells",
	"Пышные арпеджированные аккорды клавесина и праздничный шаг": "Lush arpeggiated harpsichord chords and a festive step",
	"Пробуждение лесной чащи, птичьи трели флейты и рассветный клавесин": "The forest awakening, birdlike flute trills and a dawn harpsichord",
	"Строгий старинный контрапункт с проведением темы во всех голосах": "Strict old-style counterpoint with the theme passing through every voice",
	"Виртуозная токката в духе Скарлатти с быстрыми репетициями нот": "A virtuoso Scarlatti-style toccata with rapid repeated notes",
	"Ритмичный стаккато-клавесин и удалой мотив стрелков Шервуда": "A rhythmic staccato harpsichord and a daring Sherwood archers' tune",
	"Драматическая барочная кульминация с органом и мажорным разрешением": "A dramatic baroque climax with organ and a major-key resolution",
	"Сказочные флейты, арфа и мягкий ветер": "Fairy-tale flutes, harp and a gentle wind",
	"Торжественные медные духовые и барабаны": "Solemn brass and drums",
	"Веселый средневековый танец, лютня": "A merry medieval dance, lute",
	"Мистический эмбиент-пад и колокольчики": "A mystical ambient pad and bells",
	"Ностальгическая свирель и переборы струн": "A nostalgic pipe and plucked strings",
	"Благородные валторны и струнные": "Noble French horns and strings",
	"Серебряные переливы челесты и ручей": "Silvery celesta ripples and a brook",
	"Классический клавесин в духе HoMM3": "Classic harpsichord in the spirit of HoMM3",
	"Загадочный хор предков и глубокий гонг": "A mysterious ancestral choir and a deep gong",
	"Пасторальная дудочка и птичьи трели": "A pastoral pipe and birdsong",
	"Бодрая кельтская джига и волынка": "A spirited Celtic jig and bagpipes",
	"Таинственный низкий гул и капли": "A mysterious low hum and dripping water",
	"Победные фанфары и литавры": "Victorious fanfares and timpani",
	"Мерцающие колокольчики и фортепиано": "Shimmering bells and piano",
	"Энергичный ритм и боевой марш": "An energetic rhythm and a battle march",
	"Нежная музыкальная шкатулка": "A gentle music box",
	"Величественные медные и размах гор": "Majestic brass and the sweep of the mountains",
	"Старинная баллада бродячего барда (плавный бесшовный луп)": "An old wandering bard's ballad (smooth seamless loop)",
	"Священный орган и светлые гармонии": "A sacred organ and bright harmonies",
	"Полнозвучная симфоническая увертюра": "A full-bodied symphonic overture",

	# --- Бой (battle_arena.tscn / .gd, arena_viewport.gd, encounter_data.gd) ---
	"Раунд 1": "Round 1",
	"Мана: 40 / 40": "Mana: 40 / 40",
	"Оборона": "Defend",
	"Ждать": "Wait",
	"Готовьтесь к бою!": "Prepare for battle!",
	"Книга Заклинаний": "Spellbook",
	"Закрыть (Esc)": "Close (Esc)",
	"Свойства отряда": "Stack details",
	"Статистика отряда...": "Stack stats...",
	"Враг разбит и рассеян!": "The enemy is routed and scattered!",
	"Продолжить": "Continue",
	"⚔ %s: %d-%d урона (потери %d-%d). Тапните ещё раз для атаки!": "⚔ %s: %d-%d damage (losses %d-%d). Tap again to attack!",
	"Урон: %d-%d (Потери: %d-%d)": "Damage: %d-%d (Losses: %d-%d)",
	"ШТРАФ 50%": "PENALTY 50%",
	"Вражеский отряд преграждает путь!": "An enemy detachment blocks the way!",

	# --- Карта мира: сцена (world_map.tscn) и попапы ---
	"Экран Героя (H)": "Hero Screen (H)",
	"Аларик (ур. 1)": "Alaric (lvl 1)",
	"Золото: 1500": "Gold: 1500",
	"Мана: 40/40": "Mana: 40/40",
	"Ход: 24/24": "Movement: 24/24",
	"Гл. 1: День 1": "Ch. 1: Day 1",
	"⏳ Завершить день": "⏳ End day",
	"Завершить день": "End day",
	"Завершение дня": "End of Day",
	"У героя еще остались очки хода (36/36).\nВы действительно хотите завершить день?": "The hero still has movement points (36/36).\nDo you really want to end the day?",
	"Событие": "Event",
	"Описание встречи...": "Encounter description...",
	"Действие 1": "Action 1",
	"Действие 2": "Action 2",
	"Разделение отряда": "Split Stack",
	"Отряд: Грифоны (всего: 6)": "Stack: Griffins (total: 6)",
	"Разделить": "Split",
	"✦ КНИГА ЗАКЛИНАНИЙ ✦": "✦ SPELLBOOK ✦",
	"Запас маны: 40/40 🔮  •  Сила Магии: 3": "Mana pool: 40/40 🔮  •  Spell Power: 3",
	"★ ПОХОДНЫЕ ЗАКЛИНАНИЯ (карта мира):": "★ ADVENTURE SPELLS (world map):",
	"🔮 Око Орла (10 маны)": "🔮 Eye of the Eagle (10 mana)",
	"Рассеивает пелену тумана войны в радиусе 9 клеток вокруг отряда героя.": "Lifts the fog of war within 9 tiles around the hero's party.",
	"🌿 Благодать Похода (15 маны)": "🌿 March Grace (15 mana)",
	"Восстанавливает +20% воинов во всех отрядах вашей армии прямо в походе.": "Restores +20% of the warriors in every stack of your army right on the march.",
	"🔮 Сотворить: Око Орла": "🔮 Cast: Eye of the Eagle",
	"🌿 Сотворить: Благодать": "🌿 Cast: March Grace",
	"⚔ ИЗУЧЕННЫЕ БОЕВЫЕ ЗАКЛИНАНИЯ (для тактического боя):": "⚔ LEARNED COMBAT SPELLS (for tactical battle):",
	"✦ ТЕКУЩЕЕ ЗАДАНИЕ": "✦ CURRENT QUEST",
	"Посетите Хижину Лесника (7, 18) на юге.": "Visit the Forester's Hut (7, 18) in the south.",
	"👑 ВЕЛИКИЙ ТРИУМФ! 👑": "👑 A GREAT TRIUMPH! 👑",
	"Королева Фей благодарит паладина...": "The Fairy Queen thanks the paladin...",
	"В Главное Меню": "To Main Menu",
	"Герой: Сэр Аларик (Паладин)": "Hero: Sir Alaric (Paladin)",
	"Сэр Аларик": "Sir Alaric",
	"Уровень: 1 (Глава 1)": "Level: 1 (Chapter 1)",
	"Опыт: 0 / 1000": "Experience: 0 / 1000",
	"Характеристики:": "Attributes:",
	"⚔️ Атака: 4 (+20% урон)": "⚔️ Attack: 4 (+20% damage)",
	"🛡️ Защита: 3 (-9% урон)": "🛡️ Defense: 3 (-9% damage)",
	"🔮 Сила Магии: 3": "🔮 Spell Power: 3",
	"📜 Знание: 4 (40 маны)": "📜 Knowledge: 4 (40 mana)",
	"Реликвии и Ключи:": "Relics and Keys:",
	"• Нет артефактов": "• No artifacts",
	"— Снаряжение на Герое —": "— Hero's Equipment —",
	"— Рюкзак (Нажмите для экипировки) —": "— Satchel (Click to equip) —",
	"Вторичные Навыки:": "Secondary Skills:",
	"★ НОВЫЙ УРОВЕНЬ! ★": "★ LEVEL UP! ★",
	"Сэр Аларик достигает 2 уровня!": "Sir Alaric reaches level 2!",
	"✦ Основной атрибут: +1 к Атаке!": "✦ Primary stat: +1 to Attack!",
	"Выберите вторичный навык для изучения:": "Choose a secondary skill to learn:",
	"Навык 1": "Skill 1",
	"Навык 2": "Skill 2",
	"Открыть сундук!": "Open the chest!",

	# --- Карта мира: объекты, подсказки и метки (world_view.gd) ---
	"Объект": "Object",
	"Исследовать местность": "Explore the area",
	"Старая Мельница": "The Old Mill",
	"Мельница (+500 золота в неделю)": "Mill (+500 gold per week)",
	"Мельница (Посещено)": "Mill (Visited)",
	"Священный Источник Маны": "The Sacred Mana Spring",
	"Священный Источник Жизни": "The Sacred Spring of Life",
	"Магматический Источник": "The Magma Spring",
	"Святилище (+1 Магия, мана)": "Shrine (+1 Spell Power, mana)",
	"Святилище (Мана)": "Shrine (Mana)",
	"Святилище Триумфа": "Shrine of Triumph",
	"Святыня Силы (+характеристики)": "Sanctum of Power (+attributes)",
	"Роща Лесных Лучниц": "The Forest Archers' Grove",
	"Роща Королевы Фей": "The Fairy Queen's Grove",
	"Роща Фей (Доступно: %d)": "Fairy Grove (Available: %d)",
	"Круг Друидов (Доступно: %d)": "Druid Circle (Available: %d)",
	"Гнездовье (Доступно: %d)": "Roost (Available: %d)",
	"Древний Обелиск": "The Ancient Obelisk",
	"Изумрудный Обелиск": "The Emerald Obelisk",
	"Рунический Столп Огня": "The Runic Pillar of Fire",
	"Огненный Алтарь Силы": "The Fire Altar of Power",
	"Королевская Цитадель Победы": "The Royal Citadel of Victory",
	"Хижина хранителя квеста": "The quest-giver's hut",
	"Указатель Проклятых Топей": "Signpost to the Cursed Fens",
	"Указатель Огненного Перевала": "Signpost to the Fiery Pass",
	"Врата (Нужен ключ)": "Gates (Key needed)",
	"Врата (Открыты)": "Gates (Open)",
	"Сундук (+1000 зол / +600 опыта)": "Chest (+1000 gold / +600 XP)",
	"Сундук в траве": "The Chest in the Grass",
	"Сундук у мельницы": "The Chest by the Mill",
	"Тайник в чащобе": "The Thicket Cache",
	"Сокровище Ущелья": "The Gorge Treasure",
	"Сундук в мху": "The Mossy Chest",
	"Сундук утопленника": "The Drowned Man's Chest",
	"Сокровище Склепа": "The Crypt Treasure",
	"Сундук в пепле": "The Chest in the Ashes",
	"Клад Дракона": "The Dragon's Hoard",
	"Вражеский Дозор (Орда)": "Enemy Pickets (Horde)",
	"Дозор (Разбит)": "Pickets (Routed)",
	"Стая Волков (Мельница)": "The Wolf Pack (Mill)",
	"Шайка Гоблинов (Сундук)": "The Goblin Gang (Chest)",
	"Засада Разбойников (Тракт)": "The Bandit Ambush (Highway)",
	"Страж Рощи (Древень)": "The Grove Warden (Treant)",
	"Болотные Зомби (Северная гать)": "Swamp Zombies (North Causeway)",
	"Скелеты Топей (Южный тракт)": "The Fen Skeletons (South Road)",
	"Костяная Стража Врат": "The Bone Gate Guard",
	"Легион Смерти (Северный дозор)": "The Legion of Death (North Pickets)",
	"Стражи Гробниц (Южный дозор)": "The Tomb Wardens (South Pickets)",
	"Огненный Дозор (Перевал)": "The Fire Watch (Pass)",
	"Драконьи Слуги (Кратер)": "The Dragon's Servants (Crater)",
	"Лавовые Хищники (Плато)": "The Lava Predators (Plateau)",
	"Логово Атамана": "The Chieftain's Lair",
	"Атаман Разбойников (Венец Фей)": "The Bandit Chieftain (Fairy Queen's Crown)",
	"Лагерь атамана (Сожжен)": "The Chieftain's Camp (Burned)",
	"Цитадель Лича (Кольцо Архимага)": "The Lich's Citadel (Archmage's Ring)",
	"Цитадель Лича (Разрушена)": "The Lich's Citadel (Destroyed)",
	"Красный Дракон (Панцирь Стража)": "The Red Dragon (Warden's Carapace)",
	"Логово Дракона (Повержен)": "The Dragon's Lair (Slain)",
	"📜 КВЕСТ": "📜 QUEST",
	"📜 ВЕДЬМА": "📜 WITCH",
	"⚔ БОСС": "⚔ BOSS",
	"👑 СЮДА!": "👑 HERE!",
	"🗝 ВРАТА!": "🗝 GATES!",
}
