# -*- coding: utf-8 -*-
# Переводы, батч 6: точные остатки из _missing_translations.txt + строки меню.
T = {
"Алтарь позволяет обучить ваших воинов тайным боевым искусствам:\n\n• Феи получают Двойной Выстрел (стреляют дважды за раунд!)\n• Грифоны получают Бесконечный Отпор на все атаки врагов!\n\nКазна: %d золота": "The altar teaches your warriors secret arts of war:\n\n• Fairies gain Double Shot (they fire twice per round!)\n• Griffins gain Unlimited Retaliation against every enemy attack!\n\nTreasury: %d gold",
"Атаман разбойников повержен, и вся долина избавлена от зла!\n\nСвященный Венец озаряет ваши доспехи древним золотым светом!\n\nСкорее доставьте Венец Королеве Фей в Священную Рощу (27, 4) на северо-востоке для празднования великой победы и завершения кампании!": "The bandit chieftain is vanquished, and the whole valley is delivered from evil!\n\nThe sacred Crown bathes your armor in ancient golden light!\n\nHurry — bring the Crown to the Fairy Queen in the Sacred Grove (27, 4) in the north-east, to celebrate the great victory and complete the campaign!",
"Болотная ведунья мешает зелье в котле:\n\n«Приветствую, сэр Аларик! Древний Лич восстал из затонувших склепов и погрузил край в вечный туман. Он запер перевал Костяными Вратами.\n\nВозьмите этот Костяной Ключ! Пробейтесь через нежить, уничтожьте Лича и очистите древний Алтарь Друидов!»": "The swamp witch stirs a brew in her cauldron:\n\n«Welcome, Sir Alaric! The Ancient Lich rose from the sunken crypts and drowned the land in eternal fog. He sealed the pass with the Bone Gates.\n\nTake this Bone Key! Cut your way through the undead, destroy the Lich and cleanse the ancient Druid Altar!»",
"Ваше победоносное войско вступило в туманные трясины Топей Скорби!\n\nДревний Лич осквернил святилища и поднял из болотных могил орды скелетов и зомби. Трясина бурлит темной скверной!\n\n✦ ВАШИ ЦЕЛИ В ГЛАВЕ 2:\n1. Отыщите Хижину Болотной Ведьмы (6, 17) и добудьте Костяной Ключ.\n2. Преодолейте трясину и откройте Костяные Врата (14, 11).\n3. Сокрушите Древнего Лича в Цитадели (28, 11) и очистите Алтарь Друидов (27, 4)!": "Your victorious army has entered the misty quagmires of the Fens of Sorrow!\n\nThe Ancient Lich defiled the shrines and raised hordes of skeletons and zombies from the bog graves. The mire seethes with dark blight!\n\n✦ YOUR GOALS IN CHAPTER 2:\n1. Find the Swamp Witch's Hut (6, 17) and obtain the Bone Key.\n2. Cross the mire and open the Bone Gates (14, 11).\n3. Crush the Ancient Lich at the Citadel (28, 11) and cleanse the Druid Altar (27, 4)!",
"Грифоны отвечают на все удары без устали. Отправляйте их первыми в гущу боя!": "Griffins retaliate against every blow without tiring. Send them into the thick of battle first!",
"Древний Древень пробудился от векового сна и преграждает путь к тайнику в чащобе!\nРазведка доносит: [Стражи (3 древня, 10 волков)].\nЛес защищает свои древние секреты!": "An Ancient Treant has woken from its age-long sleep and bars the way to a cache deep in the thicket!\nScouts report: [Wardens (3 treants, 10 wolves)].\nThe forest guards its ancient secrets!",
"Зловещие Костяные Врата наглухо сомкнуты. От них веет смертельным холодом.\n\nВам нужен Костяной Ключ! (Посетите Хижину Болотной Ведьмы на юго-западе).": "The sinister Bone Gates are sealed fast. A deadly chill radiates from them.\n\nYou need the Bone Key! (Visit the Swamp Witch's Hut to the south-west).",
"Зловонный трупный запах возвещает о приближении болотных зомби!\nРазведка доносит: [Орда (18 болотных зомби)].\nОни бредут прямо по настилу гати!": "A fetid stench of carrion heralds the approach of swamp zombies!\nScouts report: [A horde of 18 swamp zombies].\nThey shamble straight along the log-walk!",
"Золото из сундука можно обменять на опыт — иногда опыт ценнее казны.": "Chest gold can be traded for experience — sometimes experience is worth more than gold.",
"Из густых зарослей у южного тракта свистят стрелы разбойничьей засады!\nРазведка доносит: [Отряд (18 гоблинов, 8 волков)].\nБандиты перекрыли дорогу к хижине лесника!": "Arrows from a bandit ambush whistle from the thickets by the southern road!\nScouts report: [A band of 18 goblins, 8 wolves].\nThe brigands have blocked the way to the forester's hut!",
"Кованые врата распахнуты настежь. Дорога через горный перевал свободна!": "The wrought-iron gates stand wide open. The road through the mountain pass is clear!",
"Королева Фей со слезами радости принимает священный Венец из рук сэра Аларика!\n\nИзумрудный свет озаряет древний лес, рассеивая последние чары тьмы. Но тревожные вести приходят из Топей Скорби: Древний Лич поднимает армии нежити!\n\n★ ИТОГИ ГЛАВЫ 1: ★\n• Дней в походе: %d\n• Золото в казне: %d монет\n• Уровень Героя: %d (%s)\n• Награда Королевы: 8 Королевских Грифонов!\n\nГотовы ли вы выступить во вторую главу кампании?": "The Fairy Queen accepts the sacred Crown from Sir Alaric's hands with tears of joy!\n\nEmerald light bathes the ancient forest, dispelling the last charms of darkness. But troubling news arrives from the Fens of Sorrow: the Ancient Lich is raising armies of the undead!\n\n★ CHAPTER 1 SUMMARY: ★\n• Days on the march: %d\n• Gold in the treasury: %d coins\n• Hero level: %d (%s)\n• The Queen's reward: 8 Royal Griffins!\n\nAre you ready to march into the second chapter of the campaign?",
"Королевская Цитадель": "The Royal Citadel",
"Костяная гвардия Некрополя заступила дорогу перед Костяными Вратами!\nРазведка доносит: [Орда (22 скелета-лучника, 14 зомби)].": "The Necropolis bone guard has blocked the road before the Bone Gates!\nScouts report: [A horde of 22 skeleton archers, 14 zombies].",
"Крылатые конники рощи фей. Стремительны и первыми перехватывают вражеских стрелков!": "Winged riders of the fairy grove. Swift, and always the first to intercept enemy shooters!",
"Культ Дракона": "The Dragon Cult",
"Легендарный владыка огнедышащих пиков. Огненное дыхание пробивает на 2 гекса сквозь строй врагов!": "The legendary lord of the fire-breathing peaks. Its fiery breath pierces 2 hexes through enemy lines!",
"Легендарный владыка пламени повержен! Панцирь Древнего Стража сияет на ваших плечах!\n\nВступайте в Королевскую Цитадель (27, 4) для коронации и триумфального завершения Великой Кампании!": "The legendary lord of flame is vanquished! The Ancient Warden's Carapace shines upon your shoulders!\n\nEnter the Royal Citadel (27, 4) for your coronation and the triumphant conclusion of the Great Campaign!",
"Лесные Разбойники": "Forest Bandits",
"Массивные Железные Врата наглухо заперты стальным засовом. Из-за скал доносится вой лютых волков.\n\nВам нужен Ключ от Врат! (Посетите Хижину Лесника на юге).": "The massive Iron Gates are barred with a steel bolt. The howl of fierce wolves echoes from the crags.\n\nYou need the Gate Key! (Visit the Forester's Hut in the south).",
"Метко поражает врагов зачарованными стрелами издалека.": "Strikes foes from afar with enchanted arrows.",
"Могучий зверь с телом льва и крыльями орла. Отвечает на все удары без ограничений!": "A mighty beast with the body of a lion and the wings of an eagle. It retaliates against every blow without limit!",
"Мудрецы священных дубрав. Разит молниями природы на дальнем расстоянии.": "Sages of the sacred oak groves. They hurl nature's lightning from afar.",
"Музыка:": "Music:",
"Мятежная Гвардия": "The Rebel Guard",
"На замшелом камне высечены древние указатели:\n\n← На юг: Хижина Старого Лесника\n↑ На север: Водяная Мельница и Святилище Маны\n→ На восток: Железные Врата и Долина Разбойников\n\n[Подсказка: Пробел — исследовать место под конем, E — следующий день]": "Ancient signposts are carved into the mossy stone:\n\n← South: the Old Forester's Hut\n↑ North: the Watermill and the Mana Shrine\n→ East: the Iron Gates and the Bandit Valley\n\n[Tip: Space — search the spot beneath your horse, E — next day]",
"Нажмите, чтобы выбрать для обмена местами (или используйте ▲▼)": "Click to select for swapping places (or use ▲▼)",
"Наследие Архимага": "Archmage's Legacy",
"Наследие Архимага (2/2): +3 Сила магии, +3 Знание, +30 Мана": "Archmage's Legacy (2/2): +3 Spell Power, +3 Knowledge, +30 Mana",
"ОТРЯД": "STACK",
"Общая громкость:": "Master volume:",
"Объединить одинаковые отряды": "Merge identical stacks",
"Огненные Врата Ущелья": "The Fire Gates of the Gorge",
"Огненный дозор ущелья преграждает путь по горной тропе!\nРазведка доносит: [Орда (24 гоблина, 16 волков)].": "The gorge's fire watch blocks the mountain trail!\nScouts report: [A horde of 24 goblins, 16 wolves].",
"Ожившие изваяния древних обелисков. Отражают 30% урона от ответных и любых ближних ударов!": "Animated statues of ancient obelisks. They reflect 30% of retaliation and any melee damage!",
"Опустить ниже": "Move down",
"Опутан корнями (0 скор.)": "Rooted (0 speed)",
"Откройте Костяные Врата (14, 11) с помощью ключа ведьмы.": "Open the Bone Gates (14, 11) with the witch's key.",
"Отряд опытных бандитских стрелков устроил заслон на северной тропе!\nРазведка доносит: [Орда (26 гоблинов, 14 волков)].\nОни блокируют подходы к Священной Роще Фей!": "A band of seasoned bandit archers has set a roadblock on the northern trail!\nScouts report: [A horde of 26 goblins, 14 wolves].\nThey are blocking the approaches to the Sacred Fairy Grove!",
"ПОХОДНЫЙ ЛАГЕРЬ": "CAMPAIGN CAMP",
"Повелитель тлетворных топей. Колдует тёмное пламя по самым густым строям врага!": "The lord of the noisome fens. He casts dark flame upon the thickest enemy ranks!",
"Поднять выше": "Move up",
"Разведка докладывает: силы противника (%s) слишком велики для авторасчета без тяжелых потерь!\n\nРекомендуется провести бой лично на арене или нанять подкрепление.": "Scouts warn: the enemy force (%s) is too strong for a quick calculation without heavy losses!\n\nIt is recommended to fight the battle personally in the arena, or to hire reinforcements.",
"Роща Волшебных Фей": "The Grove of Magic Fairies",
"Русский": "Русский",
"Слить": "Merge",
"Случайная битва": "Random battle",
"Случайный Отряд Врага": "Random Enemy Detachment",
"Стая свирепых серых волков окружила подходы к старой мельнице!\nРазведка доносит: [Стая (16 волков)].\nОни жаждут крови и не пропустят вас к мукомольне!": "A pack of fierce grey wolves has surrounded the approaches to the old mill!\nScouts report: [A pack of 16 wolves].\nBloodthirsty, they will not let you reach the mill!",
"Страж Королевства": "Kingdom's Warden",
"Страж Королевства (2/3): +2 Атака, +2 Защита": "Kingdom's Warden (2/3): +2 Attack, +2 Defense",
"Страж Королевства (3/3): +4 Атака, +4 Защита, +4 Очка хода": "Kingdom's Warden (3/3): +4 Attack, +4 Defense, +4 Movement",
"Странник Просторов": "Wanderer of the Expanse",
"Странник Просторов (2/2): +6 Очков хода, +2 Атака": "Wanderer of the Expanse (2/2): +6 Movement, +2 Attack",
"Тяжело ступающие мертвецы болот. Удары заражают врага трупным ядом (-25% к атаке)!": "Heavy-treading dead of the marshes. Their blows infect the enemy with corpse poison (-25% attack)!",
"Хитрые лесные духи. 25% шанс увернуться от ближнего удара (урон вдвое меньше)!": "Cunning forest spirits. A 25% chance to evade a melee blow (damage halved)!",
"Хранительница рощи приветствует паладина:\n\n«Мы готовы направить лучниц на службу Королевству!»\n\nДоступно: %d фей-лучниц (по %d золота)\nВ вашей казне: %d золота": "The grove's keeper greets the paladin:\n\n«We are ready to send our archers into the Kingdom's service!»\n\nAvailable: %d fairy archers (at %d gold each)\nYour treasury: %d gold",
"Черный владыка топей обращен в прах! Перстень Архимага в ваших руках!\n\nСпешите к Алтарю Друидов (27, 4) на северо-востоке, чтобы завершить очищение края и получить благословение природы!": "The dark lord of the fens is turned to dust! The Archmage's Ring is in your hands!\n\nHasten to the Druid Altar (27, 4) in the north-east to complete the cleansing of the land and receive nature's blessing!",
"Шайка лесных гоблинов-грабителей делит золото возле сундука!\nРазведка доносит: [Орда (24 гоблина, 6 волков)].\nОни бросают награбленное и хватаются за топоры!": "A gang of forest goblin robbers is dividing gold by the chest!\nScouts report: [A horde of 24 goblins, 6 wolves].\nThey drop their loot and grab their axes!",
"Шумный лесной разбойник с копьем и деревянным щитом.": "A noisy forest brigand with a spear and a wooden shield.",
"Элитные белые грифоны королевской гвардии. Повышенная скорость и сокрушительный ответный удар!": "Elite white griffins of the royal guard. Increased speed and a crushing counterattack!",
"Язык:": "Language:",
"↩️ В Меню": "↩️ Menu",
"★ ВЕЛИКАЯ КАМПАНИЯ ЗАВЕРШЕНА! В Королевстве настал золотой век!": "★ THE GREAT CAMPAIGN IS COMPLETE! A golden age has dawned over the Kingdom!",
"★ ВЕНЕЦ КОРОЛЕВЫ ФЕЙ ДОБЫТ! ★": "★ THE FAIRY QUEEN'S CROWN IS RECLAIMED! ★",
"★ ГЛАВА 1 ЗАВЕРШЕНА! Отправляйтесь в Проклятые Топи (Глава 2)!": "★ CHAPTER 1 COMPLETE! Set out for the Cursed Fens (Chapter 2)!",
"★ ГЛАВА 1: ЗАЧАРОВАННЫЙ ЛЕС ★": "★ CHAPTER 1: THE ENCHANTED FOREST ★",
"★ ГЛАВА 2 ЗАВЕРШЕНА! Проклятые топи очищены от скверны!": "★ CHAPTER 2 COMPLETE! The Cursed Fens are cleansed of blight!",
"★ ГЛАВА 2: ПРОКЛЯТЫЕ ТОПИ ★": "★ CHAPTER 2: THE CURSED FENS ★",
"★ ГЛАВА 3: ПИК ДРАКОНА ★": "★ CHAPTER 3: DRAGON PEAK ★",
"★ ДРЕВНИЙ ЛИЧ СОКРУШЕН! ★": "★ THE ANCIENT LICH IS CRUSHED! ★",
"★ КРАСНЫЙ ДРАКОН ПОВЕРЖЕН! ★": "★ THE RED DRAGON IS VANQUISHED! ★",
"⚔ БРОСИТЬ ВЫЗОВ ДРАКОНУ!": "⚔ DEFY THE DRAGON!",
"⚔ В БОЙ С ОХРАНОЙ!": "⚔ FIGHT THE GUARDS!",
"⚔ В БОЙ! (Тактическая арена)": "⚔ TO BATTLE! (Tactical arena)",
"⚔ В поход: Глава 2 (Проклятые Топи) ⚔": "⚔ On the march: Chapter 2 (The Cursed Fens) ⚔",
"⚔ В поход: Глава 3 (Пик Дракона) ⚔": "⚔ On the march: Chapter 3 (Dragon Peak) ⚔",
"⚔ ОХРАНА СОКРОВИЩ!": "⚔ TREASURE GUARDS!",
"⚔ Очистить Топи от скверны!": "⚔ Cleanse the Fens of blight!",
"⚔ СОКРУШИТЬ АТАМАНА!": "⚔ CRUSH THE CHIEFTAIN!",
"⚔ СОКРУШИТЬ ЛИЧА!": "⚔ CRUSH THE LICH!",
"⚔️\nОружие": "⚔️\nWeapon",
"⚠️ СИЛЫ НЕРАВНЫ!": "⚠️ THE ODDS ARE UNEVEN!",
"⚡ Быстрый бой": "⚡ Quick battle",
"⚡ Быстрый бой (Авторасчет)": "⚡ Quick battle (Auto-resolve)",
"✓ Игра сохранена!": "✓ Game saved!",
"✦ Основной атрибут: +1 к %s!": "✦ Primary stat: +1 to %s!",
"❌ Мало маны (нужно 10 🔮)": "❌ Not enough mana (10 🔮 required)",
"❌ Мало маны (нужно 15 🔮)": "❌ Not enough mana (15 🔮 required)",
"🌿 Сотворить: Благодать (15 🔮)": "🌿 Cast: March Grace (15 🔮)",
"🏆 Тренировочный поединок на Арене успешно завершен!\nСложность: %s\nПротивник: %s\n\nВы продемонстрировали выдающееся тактическое мастерство полководца!": "The training duel in the Arena is complete!\nDifficulty: %s\nOpponent: %s\n\nYou have demonstrated the outstanding tactical mastery of a true commander!",
"👑\nШлем": "👑\nHelm",
"👑 ВЕЛИКИЙ ТРИУМФ ВСЕЙ КАМПАНИИ! 👑": "👑 THE GREAT TRIUMPH OF THE WHOLE CAMPAIGN! 👑",
"👑 ВЕРНИТЕ ВЕНЕЦ! Доставьте реликвию Королеве Фей в Священную Рощу (27, 4)!": "👑 RETURN THE CROWN! Deliver the relic to the Fairy Queen at the Sacred Grove (27, 4)!",
"👑 Венец Королевы Фей": "👑 Fairy Queen's Crown",
"👑 К Великой Победе!": "👑 Onward to victory!",
"👑 ОЧИСТИТЕ ТОПИ! Посетите Алтарь Друидов (27, 4) для завершения Главы 2!": "👑 CLEANSE THE FENS! Visit the Druid Altar (27, 4) to complete Chapter 2!",
"👑 ПОБЕДА В ГЛАВЕ 1: ЗАЧАРОВАННЫЙ ЛЕС! 👑": "👑 VICTORY IN CHAPTER 1: THE ENCHANTED FOREST! 👑",
"👑 ПОБЕДА В ГЛАВЕ 2: ПРОКЛЯТЫЕ ТОПИ! 👑": "👑 VICTORY IN CHAPTER 2: THE CURSED FENS! 👑",
"👑 ПОБЕДА! Доставьте трофеи в Королевскую Цитадель (27, 4)!": "👑 VICTORY! Bring the trophies to the Royal Citadel (27, 4)!",
"👢\nОбувь": "👢\nBoots",
"💍\nКольцо": "💍\nRing",
"💾 Слот %d": "💾 Slot %d",
"💾 Сохранить игру": "💾 Save game",
"📂 Загрузить игру": "📂 Load game",
"📜 ЛЕТОПИСЬ ПОДВИГОВ": "📜 CHRONICLE OF DEEDS",
"📜 Летопись подвигов": "📜 Chronicle of Deeds",
"📯 Рог Доблести: всё войско начинает бой на +2 инициативы!": "📯 Horn of Valor: the whole army begins the battle at +2 initiative!",
"🔮 Сотворить: Око Орла (10 🔮)": "🔮 Cast: Eye of the Eagle (10 🔮)",
"🗝 Ключ от Врат": "🗝 Gate Key",
"🛡️\nЩит": "🛡️\nShield",
"🦺\nДоспех": "🦺\nArmor",
"Настройки": "Settings",
"⚙️ Настройки": "⚙️ Settings",
"Общая громкость:": "Master volume:",
}
