# -*- coding: utf-8 -*-
# Переводы, батч 2: квесты, объекты карты, диалоги.
T = {
"«Врата открыты, паладин! Спешите на восток — разбейте атамана в его логове и верните Венец Королеве Фей!»": "«The gates are open, paladin! Hasten east — crush the chieftain in his lair and return the Crown to the Fairy Queen!»",
"«Да здравствует сэр Аларик, величайший защитник Королевства!»": "«Long live Sir Alaric, the greatest defender of the Kingdom!»",
"«Костяные Врата ждут вас, паладин! Разрушьте цитадель Лича на востоке!»": "«The Bone Gates await you, paladin! Destroy the Lich's citadel in the east!»",
"«Лесные духи-лисы желают путешествовать с вами: %d шт. (по %d золота). Казна: %d.»": "«The fox spirits wish to travel with you: %d available (at %d gold each). Treasury: %d.»",
"«Приветствую, благородный рыцарь! Мельница работает в поте лица, примите 500 золотых монет на содержание гарнизона!»": "«Welcome, noble knight! The mill works from dawn to dusk — take 500 gold coins for your garrison's upkeep!»",
"«Слава паладину! Топи снова чисты от скверны нежити!»": "«Glory to the paladin! The Fens are once again cleansed of the undead blight!»",
"«Слава сэру Аларику! Лес снова полон света и птичьего пения. Вы избавили нас от напасти!»": "«Glory to Sir Alaric! The forest is full of light and birdsong once more. You have delivered us from peril!»",
"Алтарь Очищения Топей": "Altar of the Cleansed Fens",
"Алтарь Преображения Войск": "Altar of Transfiguration",
"Алтарь осквернен темными чарами. Уничтожьте Лича в Цитадели на востоке (28, 11)!": "The altar is defiled by dark charms. Destroy the Lich at the Citadel in the east (28, 11)!",
"Алтарь позволяет обучить ваших воинов тайным боевым искусствам:\n\n• Феи получают Двойной Выстрел (стреляют дважды за раунд!)\n• Грифоны получают Бесконечный Отпор (отвечают на каждый удар!)\n• Стоимость обучения: 2000 золота за отряд": "The altar teaches your warriors secret arts of war:\n\n• Fairies gain Double Shot (they fire twice per round!)\n• Griffins gain Unlimited Retaliation (they answer every blow!)\n• Training cost: 2000 gold per stack",
"В наличии: %d страж(а) (по %d золота). Казна: %d.": "Available: %d guardian(s) (at %d gold each). Treasury: %d.",
"В Королевскую Цитадель!": "To the Royal Citadel!",
"В Священную Рощу!": "To the Sacred Grove!",
"В глубине склепа вы находите драгоценные реликвии древних времен!": "Deep in the crypt you find precious relics of ancient times!",
"В путь": "Onward",
"В путь!": "Onward!",
"Вражеский отряд": "Enemy stack",
"Врата из гигантских ребер распахнуты. Путь свободен!": "The gates of giant ribs swing open. The way is clear!",
"Все грифоны уже наняты на этой неделе!": "All griffins have already been hired this week!",
"Все друиды уже присоединились к вашему войску на этой неделе!": "All druids have already joined your army this week!",
"Все стражи уже следуют за вами. Новые восстанут к следующей неделе.": "All guardians already follow you. New ones will rise next week.",
"Все феи-лучницы уже наняты на этой неделе!\n\nНовые добровольцы прибудут с началом новой недели (День 8).": "All fairy archers have already been hired this week!\n\nNew volunteers will arrive with the new week (Day 8).",
"Вы вставляете ключ Лесника в замковую скважину. Раздается гулкий щелчок — массивные железные створки со скрипом распахиваются!\n\nПроход в Долину Разбойников открыт!": "You slide the Forester's key into the lock. A hollow click rings out — the massive iron gates groan open!\n\nThe way into the Bandit Valley is clear!",
"Вы применяете Костяной Ключ ведьмы. Останки со скрежетом расходятся в стороны!\n\nПроход к Цитадели Лича открыт!": "You use the Witch's Bone Key. The remains grind apart!\n\nThe way to the Lich's Citadel is open!",
"Выбрать: %s": "Choose: %s",
"Выделить в новый отряд: %d": "Split into a new stack: %d",
"Выделить в новый отряд: 1": "Split into a new stack: 1",
"Выйти в главное меню": "Exit to main menu",
"Выступить в поход!": "Begin the campaign!",
"Гл. %d • День %d": "Ch. %d • Day %d",
"Главарь разбойников повержен!\n\n★ ВЫ ВЕРНУЛИ ВЕНЕЦ КОРОЛЕВЫ ФЕЙ! ★\nПолучен легендарный артефакт: Венец Королевы Фей!\nОтнесите его в Рощу Фей на севере!\n\nНаграда:\nЗолото: +%d\nОпыт: +%d": "The bandit chieftain is vanquished!\n\n★ YOU HAVE RECLAIMED THE FAIRY QUEEN'S CROWN! ★\nLegendary artifact received: the Fairy Queen's Crown!\nCarry it to the Fairy Grove in the north!\n\nReward:\nGold: +%d\nExperience: +%d",
"Гнездовье Королевских Грифонов": "Royal Griffin Roost",
"Гордые грифоны готовы взмыть в бой:\n\nДоступно: %d грифонов (по %d золота)\nКазна: %d золота": "Proud griffins are ready to soar into battle:\n\nAvailable: %d griffins (at %d gold each)\nTreasury: %d gold",
"Горн тихо потрескивает. Кузнецы уже оснастили ваше войско.": "The forge crackles softly. The smiths have already outfitted your army.",
"Древний Лич": "The Ancient Lich",
"Древний Лич развеян в прах, и животворный свет возвращается в болота!\n\n★ ИТОГИ ГЛАВЫ 2: ★\n• Дней в походе: %d\n• Золото в казне: %d монет\n• Уровень Героя: %d\n• Награда: Перстень Архимага и отряд Друидов!\n\nГорные вестники приносят тревожную весть: на Пике Дракона пробудился древний властелин огня!": "The Ancient Lich is scattered to dust, and life-giving light returns to the fens!\n\n★ CHAPTER 2 SUMMARY: ★\n• Days on the march: %d\n• Gold in the treasury: %d coins\n• Hero level: %d\n• Reward: the Archmage's Ring and a stack of Druids!\n\nMountain heralds bring troubling news: an ancient lord of fire has awakened on Dragon Peak!",
"Древний Лич сокрушен и обращен в прах!\n\n★ ПРОКЛЯТЫЕ ТОПИ ОЧИЩЕНЫ! ★\nПолучен могущественный артефакт: Перстень Архимага!\nПосетите Алтарь Друидов для завершения Главы 2!\n\nНаграда:\nЗолото: +%d\nОпыт: +%d": "The Ancient Lich is crushed and turned to dust!\n\n★ THE CURSED FENS ARE CLEANSED! ★\nA mighty artifact received: the Archmage's Ring!\nVisit the Druid Altar to complete Chapter 2!\n\nReward:\nGold: +%d\nExperience: +%d",
"Древний Обелиск Силы": "The Ancient Obelisk of Power",
"Древний склеп пуст.": "The ancient crypt is empty.",
"Друиды благодарят сэра Аларика:\n\n«Спасибо за избавление, паладин! Проклятие снято навсегда!»": "The druids thank Sir Alaric:\n\n«Thank you for our deliverance, paladin! The curse is lifted forever!»",
"Жуткие личи и скелеты охраняют проклятые сокровища древнего склепа!\nРазведка доносит: [Тьма (4 лича, 20 скелетов, 12 зомби)].": "Dread liches and skeletons guard the cursed treasures of the ancient crypt!\nScouts report: [Darkness (4 liches, 20 skeletons, 12 zombies)].",
"Забрать 1000 золота в казну": "Take 1000 gold for the treasury",
"Забрать сокровища (+1200 золота)": "Take the treasure (+1200 gold)",
"Загрузить игру из выбранного слота": "Load the game from the chosen slot",
"Запас маны: %d / %d 🔮  •  Сила Магии: %d": "Mana pool: %d / %d 🔮  •  Spell Power: %d",
"Затонувший Склеп": "The Sunken Crypt",
"Зловещие Костяные Врата наглухо сомкнуты. От них веет смертельным холодом.\n\nВам нужен Костяной Ключ! (Посетите Хижину Болотной Ведьмы на юго-западе)": "The sinister Bone Gates are sealed fast. A deadly chill radiates from them.\n\nYou need the Bone Key! (Visit the Swamp Witch's Hut to the south-west)",
"Золотой век настал!": "",
"Из густых зарослей у южного тракта свистят стрелы разбойничьей засады!\nРазведка доносит: [Отряд (18 гоблинов, 8 волков)].\nБандиты перекрыли дорогу кForester's hut!": "",
"Из густых зарослей у южного тракта свистят стрелы разбойничьей засады!\nРазведка доносит: [Отряд (18 гоблинов, 8 волков)].\nБандиты перекрыли дорогу к хижине Лесника!": "Arrows from a bandit ambush whistle from the thickets by the southern road!\nScouts report: [A band of 18 goblins, 8 wolves].\nThe brigands have blocked the way to the Forester's hut!",
"Из-за скал перевала выступает тяжелый авангард разбойников!\nРазведка доносит: [Орда (25 гоблинов, 12 волков)].\nОни охраняют восточную долину атамана!": "A heavy bandit vanguard advances from the pass rocks!\nScouts report: [A horde of 25 goblins, 12 wolves].\nThey guard the chieftain's eastern valley!",
"Изучить надгробные руны (+800 опыта)": "Study the tomb runes (+800 experience)",
"Испить из источника": "Drink from the spring",
"Используйте Ключ Лесника, чтобы открыть Железные Врата (14, 11) в Долину.": "Use the Forester's Key to open the Iron Gates (14, 11) into the Valley.",
"Исследуйте огненный перевал и откройте Огненные Врата (14, 11)!": "Explore the fiery pass and open the Fire Gates (14, 11)!",
"К Алтарю Друидов!": "To the Druid Altar!",
"Квест: Похищенный Венец": "Quest: The Stolen Crown",
"Квест: Проклятые Топи": "Quest: The Cursed Fens",
"Кованые врата распахнуты настежь. Дорога на Пик Дракона свободна!": "The wrought-iron gates stand wide open. The road to Dragon Peak is clear!",
"Колесо мерно вращается в потоке воды. Мельник уже одарил ваше войско на этой неделе.": "The wheel turns steadily in the stream. The miller has already gifted your army this week.",
"Королева Фей со скорбью в голосе молвит:\n\n«Атаман разбойников украл наш священный Венец... Без него наш народ слабеет, а деревья чахнут.\nУмоляю вас, верните Венец из лагеря атамана на востоке!»": "The Fairy Queen speaks with sorrow:\n\n«The bandit chieftain has stolen our sacred Crown... Without it our people weaken and the trees wither.\nWe implore you — bring back the Crown from the chieftain's camp in the east!»",
"Королева Фей тепло улыбается вам:\n\n«Свет и гармония вернулись в сказочный лес. Спасибо за верность и отвагу, сэр Аларик! Вы навсегда наш великий герой и спаситель!»": "The Fairy Queen smiles warmly at you:\n\n«Light and harmony have returned to the fairy-tale forest. Thank you for your loyalty and courage, Sir Alaric! You will forever be our great hero and savior!»",
"Костяная Стража": "The Bone Guard",
"Костяные Врата Некрополя": "The Necropolis Bone Gates",
"Красный Дракон": "The Red Dragon",
"Красный Дракон повержен в легендарном поединке!\n\n★ ТРИУМФ НАД ПЛАМЕНЕМ! ★\nПолучен легендарный Панцирь Древнего Стража!\nВы покорили Пик Дракона и спасли Королевство!\n\nНаграда:\nЗолото: +%d\nОпыт: +%d": "The Red Dragon is vanquished in a legendary duel!\n\n★ TRIUMPH OVER FLAME! ★\nA legendary artifact received: the Ancient Warden's Carapace!\nYou have conquered Dragon Peak and saved the Kingdom!\n\nReward:\nGold: +%d\nExperience: +%d",
"Красный Дракон повержен! Владыка небес склонился перед доблестью паладина Аларика!\n\nВсе угрозы Королевству устранены, реликвии возвращены, а мир воцарился во всех землях на тысячу лет!\n\n★ ИТОГИ ВЕЛИКОЙ КАМПАНИИ: ★\n• Пройдено глав: 3 из 3\n• Дней в походе: %d\n• Золото в казне: %d\n• Уровень Героя: %d\n• Артефакты: Полный комплект реликвий Королевства!\n\nКороль жалует вам высший титул «Маршал Королевства»!": "The Red Dragon is vanquished! The lord of the skies bows before the valor of paladin Alaric!\n\nEvery threat to the Kingdom is ended, the relics returned, and peace reigns over all lands for a thousand years!\n\n★ SUMMARY OF THE GREAT CAMPAIGN: ★\n• Chapters completed: 3 of 3\n• Days on the march: %d\n• Gold in the treasury: %d\n• Hero level: %d\n• Artifacts: the full regalia of the Kingdom!\n\nThe King grants you the highest title of «Marshal of the Realm»!",
"Круг Болотных Друидов": "The Circle of Swamp Druids",
"Крылатые пегасы готовы служить: %d шт. (по %d золота). Казна: %d.": "Winged pegasi stand ready to serve: %d available (at %d gold each). Treasury: %d.",
"Кузница Горных Владык": "The Forge of Mountain Lords",
"Лавовые Хищники": "The Lava Predators",
"Лавовые хищники кружат над плато у Королевской Цитадели!\nРазведка доносит: [Стая (12 грифонов, 22 гоблина)].": "Lava predators circle the plateau by the Royal Citadel!\nScouts report: [A flock of 12 griffins, 22 goblins].",
"Легендарный владыка пламени повержен! Панцирь Древнего Стража сияет на ваших плечах!\n\nВступайте в Королевскую Цитадель (27, 4) для коронации и триумфа!": "The legendary lord of flame is vanquished! The Ancient Warden's Carapace shines upon your shoulders!\n\nEnter the Royal Citadel (27, 4) for your coronation and triumph!",
"Легион Смерти": "The Legion of Death",
"Легион Тьмы патрулирует дорогу к Алтарю Друидов!\nРазведка доносит: [Орда (24 скелета-лучника, 18 зомби)].": "A Legion of Darkness patrols the road to the Druid Altar!\nScouts report: [A horde of 24 skeleton archers, 18 zombies].",
"Лесные разбойники": "Forest Bandits",
"Логово Атамана Разбойников": "The Bandit Chieftain's Lair",
"МИНИ-КАРТА": "MINI-MAP",
"Марш прерван": "March halted",
"Мастера кузнечного дела перековывают ваши доспехи и мечи!\n\n+2 к Атаке, +2 к Защите паладина!": "The master smiths reforge your armor and blades!\n\n+2 Attack, +2 Defense for the paladin!",
"Навык Лидерства даёт отрядам шанс на дополнительный ход. Прокачивайте!": "Leadership gives your stacks a chance of an extra turn. Level it up!",
"Надеть: %s %s [%s]": "Equip: %s %s [%s]",
"Нанять Каменного Стража (%d зол.)": "Hire a Stone Guardian (%d gold)",
"Нанять всех доступных (%d фей за %d зол.)": "Hire all available (%d fairies for %d gold)",
"Нанять грифонов (%d за %d зол.)": "Hire griffins (%d for %d gold)",
"Нанять лис-оборотней (%d за %d зол.)": "Hire fox shifters (%d for %d gold)",
"Нанять отряд (%d друидов за %d зол.)": "Hire the stack (%d druids for %d gold)",
"Нанять отряд (%d фей за %d зол.)": "Hire the stack (%d fairies for %d gold)",
"Нанять пегасов (%d за %d зол.)": "Hire pegasi (%d for %d gold)",
"Настройки звука:": "Sound settings:",
"Недостаточно золота": "Not enough gold",
"Недостаточно золота (нужно %d зол.)": "Not enough gold (%d gold required)",
"Недостаточно золота (нужно хотя бы %d зол.)": "Not enough gold (at least %d gold required)",
"Нет": "No",
"Небесная Молния поражает %s на %d урона! (Потери: %d)": "Heavenly Lightning strikes %s for %d damage! (Losses: %d)",
"Небо объято багровым заревом. Сразите Красного Дракона на Пике (28, 11)!": "The sky glows crimson. Defeat the Red Dragon at the Peak (28, 11)!",
"Око Орла рассеивает туман войны!": "",
"Оплетенные корнями": "",
"Отряд опытных бандитских стрелков устроил заслон на северной тропе!\nРазведка доносит: [Орда (26 гоблинов, 14 волков)].\nОни блокируют подходы к Священной Роще!": "A band of seasoned bandit archers has set a roadblock on the northern trail!\nScouts report: [A horde of 26 goblins, 14 wolves].\nThey are blocking the approaches to the Sacred Grove!",
"Открыто подвигов: %d из %d": "Deeds unlocked: %d of %d",
"Отложить действие до конца раунда (клавиша W)": "Postpone the action to the end of the round (key W)",
"Отойти": "Step away",
"Отряд: %s (всего: %d)": "Stack: %s (total: %d)",
"Отступить": "Retreat",
"Отступить назад": "Fall back",
"Очки хода исчерпаны. Завершите день (клавиша E или кнопка \"Завершить день\"), чтобы выступить в новый путь!": "Movement points are exhausted. End the day (key E or the \"End Day\" button) to set out on a new road!",
"Перед вами вздымаются багровые скалы Огненного Пика!\n\nКрасный Дракон пробудился и сжигает горные перевалы. Это решающая битва за спасение всего Королевства!\n\n✦ ВАШИ ЦЕЛИ В ГЛАВЕ 3:\n1. Скуйте легендарную броню в Кузнице Владык (10, 4).\n2. Преодолейте Огненные Врата Ущелья (14, 11).\n3. Сокрушите Красного Дракона на вершине Пика (28, 11) и прибудьте в Цитадель (27, 4)!": "Crimson cliffs of the Fiery Peak rise before you!\n\nThe Red Dragon has awakened and burns the mountain passes. This is the decisive battle for the salvation of the whole Kingdom!\n\n✦ YOUR GOALS IN CHAPTER 3:\n1. Forge legendary armor at the Forge of Lords (10, 4).\n2. Overcome the Fire Gates of the gorge (14, 11).\n3. Crush the Red Dragon at the summit (28, 11) and arrive at the Citadel (27, 4)!",
"Перед вами владыка пламени — легендарный Красный Дракон!\nВоздух дрожит от нестерпимого жара!\n\nЭто финальная битва за судьбу Королевства!": "Before you stands the lord of flame — the legendary Red Dragon!\nThe air trembles with unbearable heat!\n\nThis is the final battle for the fate of the Kingdom!",
"Перед вами главная цитадель разбойников!\nЗдесь засел свирепый Атаман со сворой волков и оскверненным древнем [Тьма (50+ врагов)]!\n\nОни охраняют похищенный Венец Королевы Фей!": "Before you lies the bandits' main citadel!\nHere lurks the fierce Chieftain with his wolf pack and a corrupted treant [Darkness (50+ enemies)]!\n\nThey guard the stolen Crown of the Fairy Queen!",
"Перед вами массивные Огненные Врата. Руны вспыхивают ярким светом под вашей рукой, и тяжелые створки распахиваются!": "Before you loom the massive Fire Gates. The runes flare bright at your touch, and the heavy doors swing open!",
"Перед вами оплот черного колдовства!\nДревний Лич поднимает легион скелетов и болотных зомби!\n\nОни охраняют Перстень Архимага!": "Before you rises a stronghold of black sorcery!\nThe Ancient Lich raises a legion of skeletons and swamp zombies!\n\nThey guard the Archmage's Ring!",
"Пик Красного Дракона": "The Red Dragon's Peak",
"Поклониться": "Bow",
"Понятно": "Understood",
"Посетите Хижину Болотной Ведьмы (6, 17), чтобы получить Костяной Ключ.": "Visit the Swamp Witch's Hut (6, 17) to obtain the Bone Key.",
"Посетите Хижину Лесника (7, 18) на юге, чтобы узнать о беде и получить Ключ от Врат.": "Visit the Forester's Hut (7, 18) in the south to learn of the trouble and receive the Gate Key.",
"Походный лагерь и настройки": "Campaign camp and settings",
"Превосходно!": "Splendid!",
"Прикоснувшись к руническому монолиту, вы чувствуете, как тело наполняется силой легендарных героев прошлого!\n\n+2 к Атаке, +2 к Защите!": "Touching the runic monolith, you feel your body fill with the strength of legendary heroes of old!\n\n+2 Attack, +2 Defense!",
"Принять 500 золота": "Accept 500 gold",
"Принять Костяной Ключ": "Accept the Bone Key",
"Принять ключ и отправиться в поход": "Take the key and set out",
"Принять работу кузнецов": "Accept the smiths' work",
"Принять силу предков": "Accept the ancestors' strength",
"Продвинутый": "Advanced",
"Продолжить поход": "Continue the journey",
"Продолжить путь": "Continue on",
"Пройти к логову Дракона": "Proceed to the Dragon's lair",
"Пройти через врата": "Pass through the gates",
"Пусто": "Empty",
"Путевой Камень": "Waystone",
"Разбойничий дозор": "Brigand Pickets",
"Разведка докладывает: силы противника (%s) слишком велики для авторасчета без тяжелых потерь!\n\nРекомендуется провести бой лично на арене и сохранить войско!": "Scouts warn: the enemy force (%s) is too strong for a quick calculation without heavy losses!\n\nIt is recommended to fight the battle personally in the arena to spare your army!",
"Раздать крестьянам (+600 опыта)": "Give to the peasants (+600 experience)",
"Разделить отряд": "Split stack",
"Руны гаснут: стражи Обелиска пали в бою, и древние изваяния признали вашу доблесть. Один из Каменных Стражей готов следовать за вами!": "The runes fade: the Obelisk's guards have fallen in battle, and the ancient statues acknowledge your valor. One of the Stone Guardians is ready to follow you!",
"Рыцарь Аларик достигает %d уровня!": "Sir Alaric reaches level %d!",
"Святилище Маны": "The Mana Shrine",
"Священная Роща Королевы Фей": "The Fairy Queen's Sacred Grove",
"Священная энергия наполняет лагерь рыцаря! Раненые воины исцелены, и ряды войска пополнены (+20% бойцов во всех отрядах)!": "Sacred energy fills the knight's camp! The wounded are healed and the ranks replenished (+20% warriors in every stack)!",
"Священное сияние окутывает алтарь.\n\nВсе отряды вашего войска уже достигли высшей ступени развития!": "Holy radiance envelops the altar.\n\nEvery stack of your army has already reached its highest form!",
"Скелеты Топей": "The Fen Skeletons",
"Скелеты-лучники поднимают костяные луки среди болотного мха!\nРазведка доносит: [Орда (20 скелетов-лучников)].\nОни перекрыли тропу к Хижине Ведьмы!": "Skeleton archers raise bone bows among the bog moss!\nScouts report: [A horde of 20 skeleton archers].\nThey have blocked the trail to the Witch's Hut!",
"Слава Свету!": "Glory to the Light!",
"Слепой враг пропускает ход, пока не получит урон. Ослепляйте самых опасных!": "A blinded enemy skips its turn until it takes damage. Blind the most dangerous foes!",
"Слот: %s (Свободен)\nВыберите артефакт в рюкзаке ниже": "Slot: %s (Empty)\nChoose an artifact from the satchel below",
"Слоты сохранений (1-3):": "Save slots (1-3):",
"Слуги Дракона": "The Dragon's Servants",
"Слуги дракона не подпускают никого к жерлу вулкана!\nРазведка доносит: [Орда (25 гоблинов, 16 волков, 4 древня)].": "The dragon's servants let no one near the volcano's maw!\nScouts report: [A horde of 25 goblins, 16 wolves, 4 treants].",
"Сокрушите Атамана разбойников (28, 11) на востоке долины и верните похищенный Венец!": "Crush the Bandit Chieftain (28, 11) in the east of the valley and reclaim the stolen Crown!",
"Сокрушите Древнего Лича в Цитадели (28, 11) на востоке топей!": "Crush the Ancient Lich at the Citadel (28, 11) in the east of the fens!",
"Сокровища Обелиска": "",
"Сразитесь с Красным Драконом на вершине Пика (28, 11)!": "Battle the Red Dragon at the summit of the Peak (28, 11)!",
"Среди трав вы нашли дубовый сундук, набитый золотом и самоцветами!\n\nЧто вы решите сделать?": "Among the grasses you find an oak chest stuffed with gold and gemstones!\n\nWhat will you do?",
"Старая Водяная Мельница": "The Old Watermill",
"Старый лесничий взволнован:\n\n«Беда, сэр Аларик! Шайка разбойников из ущелья похитила древний Венец Королевы Фей! Без него гибнет вся магия нашего леса. Бандиты заперли ущелье Железными Вратами.\n\nВот кованый Ключ от Врат! Прогоните атамана и отнесите Венец в Рощу Фей на севере долины!»": "The old forester is anxious:\n\n«Trouble, Sir Alaric! A bandit gang from the gorge has stolen the ancient Crown of the Fairy Queen! Without it all the magic of our forest is dying. The bandits sealed the gorge with the Iron Gates.\n\nHere is the wrought Gate Key! Drive off the chieftain and carry the Crown to the Fairy Grove in the north of the valley!»",
"Стая Волков": "The Wolf Pack",
"Стая свирепых серых волков окружила подходы к старой мельнице!\nРазведка доносит: [Стая (16 волков)].\nОни жаждут крови и не пропустят вас к мельнице!": "A pack of fierce grey wolves has surrounded the approaches to the old mill!\nScouts report: [A pack of 16 wolves].\nBloodthirsty, they will not let you reach the mill!",
"Страж Рощи": "The Grove Warden",
"Стража Врат": "The Gate Watch",
"Стража Обелиска": "The Obelisk Guard",
"Стража Огненных Врат охраняет вход в цитадель перевала!\nРазведка доносит: [Орда (22 скелета, 25 гоблинов, 14 волков)].": "The Fire Gate watch guards the entrance to the citadel of the pass!\nScouts report: [A horde of 22 skeletons, 25 goblins, 14 wolves].",
"Стража ущелья": "The Gorge Watch",
"Стражи Гробниц": "The Tomb Wardens",
"Стрелки бьют вдвое слабее, если враг подошёл вплотную — прикрывайте фей-лучниц!": "Shooters deal half damage when enemies close in — shield your fairy archers!",
"Сундук с Сокровищами": "The Treasure Chest",
"У героя еще остались очки хода (%d/%d).\nВы действительно хотите завершить день?": "The hero still has movement points left (%d/%d).\nDo you really want to end the day?",
"Улучшить %s -> %s (%d шт. за %d зол.)": "Upgrade %s -> %s (%d warriors for %d gold)",
"Уровень: %d (Глава %d)": "Level: %d (Chapter %d)",
"Файл сохранения не найден": "Save file not found",
"Хижина Болотной Ведьмы": "The Swamp Witch's Hut",
"Хижина Старого Лесника": "The Old Forester's Hut",
"Ход: %d/%d": "Movement: %d/%d",
"Хранительница рощи приветствует паладина:\n\n«Мы готовы направить лучниц на службу Королевству!»\n\nДоступно: %d фей-лучниц (по %d золота)\nКазна: %d золота": "The grove's keeper greets the paladin:\n\n«We are ready to send our archers into the Kingdom's service!»\n\nAvailable: %d fairy archers (at %d gold each)\nTreasury: %d gold",
"Центрировать камеру на герое": "Center camera on hero",
"Цитадель Древнего Лича": "The Ancient Lich's Citadel",
"Черный владыка топей обращен в прах! Перстень Архимага в ваших руках!\n\nСпешите к Алтарю Друидов (27, 4) на северо-востоке, чтобы завершить главу!": "The dark lord of the fens is turned to dust! The Archmage's Ring is in your hands!\n\nHasten to the Druid Altar (27, 4) in the north-east to complete the chapter!",
"Шайка Гоблинов": "The Goblin Gang",
"Шайка лесных гоблинов-грабителей делит золото возле сундука!\nРазведка доносит: [Орда (24 гоблина, 6 волков)].\nОни бросают награбленное и хватают копья!": "A gang of forest goblin robbers is dividing gold by the chest!\nScouts report: [A horde of 24 goblins, 6 wolves].\nThey drop their loot and grab their spears!",
"Эксперт": "Expert",
"Базовый": "Basic",
"Элитная личная гвардия Атамана охраняет Древний Обелиск и сокровищницу!\nРазведка доносит: [Орда (3 древня, 20 гоблинов, 10 волков)].": "The Chieftain's elite personal guard watches over the Ancient Obelisk and its treasure house!\nScouts report: [A horde of 3 treants, 20 goblins, 10 wolves].",
"Этот сундук охраняет %s!\n\nВраги замечают ваше приближение, обнажают оружие и нападают на вас!\nСначала одолейте охрану, чтобы забрать сокровища!": "This chest is guarded by %s!\n\nThe enemies spot your approach, draw their weapons and attack!\nDefeat the guards first to claim the treasure!",
"Я в пути!": "I'm on my way!",
"Я выполню долг!": "I shall do my duty!",
"Я найду его!": "I will find it!",
"Я одолею дракона!": "I will conquer the dragon!",
"Я сокрушу его!": "I will crush him!",
"Ясно": "Understood",
"день %d": "day %d",
"Сохранить игру в выбранный слот": "Save the game to the chosen slot",
"Спасибо, буду знать!": "Thank you, good to know!",
"💡 Совет дня": "💡 Tip of the day",
}
