# -*- coding: utf-8 -*-
# Переводы, батч 1: боевой лог и плавающие тексты арены.
T = {
"  Ответный удар: %s наносит %d урона! (Потери: %d)": "  Retaliation: %s strikes for %d damage! (Losses: %d)",
" (+%d от снаряжения)": " (+%d from gear)",
" (Уже ждал)": " (Already waited)",
" [Без ответа]": " [No retaliation]",
" [Враг ответит!]": " [Enemy will retaliate!]",
"%s %s (%s уровень)\n%s": "%s %s (%s level)\n%s",
"%s (%d маны)\n%s": "%s (%d mana)\n%s",
"%s (ур. %d)": "%s (lvl %d)",
"%s атакует %s и наносит %d урона! (Потери: %d)": "%s attacks %s and deals %d damage! (Losses: %d)",
"%s благословлен святым сиянием на 3 раунда!": "%s is blessed with holy radiance for 3 rounds!",
"%s встает в глухую оборону (+30%% к защите)!": "%s braces for a stalwart defense (+30%% defense)!",
"%s ослеплен яркой вспышкой и не может действовать!": "%s is blinded by a dazzling flash and cannot act!",
"%s покрыт каменной броней (+5 к Защите на 3 раунда)!": "%s is clad in stone hide (+5 Defense for 3 rounds)!",
"%s получает ускорение (+3 к скорости)!": "%s is hasted (+3 Speed)!",
"%s скован леденящим инеем (скорость снижена на 50%% на 3 раунда)!": "%s is bound by freezing frost (Speed halved for 3 rounds)!",
"\n\n⚔ Итоги боя: раундов %d | урон %d | потери врага %d | свои потери %d": "\n\n⚔ Battle summary: %d rounds | damage dealt %d | enemy losses %d | own losses %d",
"\n\n📯 Найден артефакт: Рог Доблести! Наденьте его в профиле героя.": "\n\n📯 Artifact found: Horn of Valor! Equip it in the hero profile.",
"\n\n🧥 Найден артефакт: Плащ Странника! Наденьте его в профиле героя.": "\n\n🧥 Artifact found: Wanderer's Mantle! Equip it in the hero profile.",
"\n👑 ПОЛУЧЕН ВЕНЕЦ КОРОЛЕВЫ ФЕЙ!": "\n👑 THE FAIRY QUEEN'S CROWN HAS BEEN RECLAIMED!",
"\n💍 ПОЛУЧЕН ПЕРСТЕНЬ АРХИМАГА!": "\n💍 THE ARCHMAGE'S RING HAS BEEN CLAIMED!",
"\n🦺 ПОЛУЧЕН ПАНЦИРЬ ДРЕВНЕГО СТРАЖА!": "\n🦺 THE ANCIENT WARDEN'S CARAPACE HAS BEEN CLAIMED!",
"БЛАГОСЛОВЕНИЕ!": "BLESSING!",
"Вражеский отряд преграждает путь (%s)!\nРазведка оценивает силы противника: [Орда (20-40 бойцов)].\nОни готовы вступить в схватку!": "An enemy detachment blocks the path (%s)!\nScouts estimate the enemy force: [A horde of 20-40 fighters].\nThey are ready for a fight!",
"Ваша армия стремительно сокрушила врага (%s)!\n\nПотери войска:\n%s\nПолучено награды:\n💰 Золото: +%d\n⭐ Опыт: +%d%s": "Your army swiftly crushed the enemy (%s)!\n\nArmy losses:\n%s\nRewards received:\n💰 Gold: +%d\n⭐ Experience: +%d%s",
"Ваши воины были вынуждены отступить.\nВраг остался на своей позиции!\nПерегруппируйтесь и попробуйте снова!": "Your warriors were forced to retreat.\nThe enemy holds its ground!\nRegroup and try again!",
"Ваши воины пали на Арене!\nСложность: %s\n\nСмените тактику, подберите другой состав отрядов и попробуйте снова!": "Your warriors have fallen in the Arena!\nDifficulty: %s\n\nChange your tactics, pick a different army and try again!",
"Великолепно!": "Magnificent!",
"Ваше войско": "Your army",
"Герой уже сотворил заклинание в этом раунде!": "The hero has already cast a spell this round!",
"Глухая оборона (+30% защ.)": "Stalwart Defense (+30% def.)",
"Заклинание %s можно применить только к вражескому отряду!": "The spell %s can only target an enemy stack!",
"Заклинание %s можно применить только к союзному отряду!": "The spell %s can only target an allied stack!",
"Исцеление: отряд %s восстанавливает %d ед. здоровья!": "Heal: the stack %s restores %d health!",
"КАМЕННАЯ КОЖА (+5)": "STONE SKIN (+5)",
"Каменная кожа (+5 защ., %d р.)": "Stone Skin (+5 def., %d r.)",
"Благословение (%d р.)": "Blessing (%d r.)",
"Болезнь (-25%% атк., %d р.)": "Disease (-25%% att., %d r.)",
"Ускорение (%d р.)": "Haste (%d r.)",
"Ослепление (%d р.)": "Blinded (%d r.)",
"МОЛНИЯ -%d": "LIGHTNING -%d",
"ОГОНЬ -%d": "FIRE -%d",
"ОСЛЕПЛЕНИЕ!": "BLINDED!",
"ПРОЗРЕНИЕ!": "SEE AGAIN!",
"ПОРАЖЕНИЕ...": "DEFEAT...",
"Потери: -%d": "Losses: -%d",
"Регенерация (+20 HP в раунд)": "Regeneration (+20 HP per round)",
"Раунд %d": "Round %d",
"Режим автобоя выключен. Ручное управление.": "Auto-battle disabled. Manual control.",
"СЛАВНАЯ ПОБЕДА!": "GLORIOUS VICTORY!",
"УСКОРЕНИЕ!": "HASTED!",
"Отряд уже ждал в этом раунде и обязан действовать!": "This stack has already waited this round and must act!",
"Отражение (%d%% ближнего урона)": "Reflection (%d%% of melee damage)",
"Уклонение (%d%% шанс вдвое снизить ближний урон)": "Evasion (%d%% chance to halve melee damage)",
"Стрелок (дальность 5 гексов)": "Shooter (range 5 hexes)",
"Огненное дыхание (пробивает насквозь)": "Fire Breath (pierces through)",
"Трупный яд (ослабляет атаку)": "Corpse Poison (weakens attack)",
"Оплетающие корни": "Entangling Roots",
"Бесконечный отпор": "Unlimited Retaliation",
"Колдун (тёмное пламя по густым строям)": "Caster (dark flame at the thickest ranks)",
"Обычные боевые навыки": "Ordinary combat skills",
"Замедление": "Slow",
"Каменная Кожа": "Stone Skin",
"Ослепление": "Blind",
"Благословение": "Blessing",
"Ускорение": "Haste",
"Исцеление": "Heal",
"Огненный Шар": "Fireball",
"Молния": "Lightning",
"Вдохновение": "Inspiration",
"Щит Света": "Shield of Light",
"Возмездие": "Retribution",
"Око Орла": "Eye of the Eagle",
"Благодать Похода": "March Grace",
"⚡ [СЛОМАННАЯ СТРЕЛА! Дистанция %d > 5, Штраф -50%%]: Урон %d-%d (Потери: %d-%d)": "⚡ [BROKEN ARROW! Distance %d > 5, penalty -50%%]: Damage %d-%d (Losses: %d-%d)",
"⚡ Авто": "⚡ Auto",
"⚡ БЫСТРЫЙ БОЙ: ПОБЕДА!": "⚡ QUICK BATTLE: VICTORY!",
"⚡ Режим автобоя ВКЛЮЧЕН!": "⚡ Auto-battle ENABLED!",
"⚡ Сломанная стрела! %s наносит %d урона (штраф 50%%) по %s! (Потери: %d)": "⚡ Broken arrow! %s deals %d damage (penalty 50%%) to %s! (Losses: %d)",
"⚔ %s осенен печатью Возмездия: ближние атакующие получат 25%% урона ответно (3 раунда)!": "⚔ %s is sealed with Retribution: melee attackers will suffer 25%% of the damage in return (3 rounds)!",
"⚔ [РУКОПАШНАЯ (СТРЕЛОК В УПОР, ШТРАФ -50%%)]: Урон %d-%d (Потери: %d-%d)%s": "⚔ [MELEE (SHOOTER AT CLOSE RANGE, PENALTY -50%%)]: Damage %d-%d (Losses: %d-%d)%s",
"⚔ [РУКОПАШНАЯ АТАКА]: Урон %d-%d (Потери: %d-%d)%s": "⚔ [MELEE ATTACK]: Damage %d-%d (Losses: %d-%d)%s",
"⚔ ВОЗМЕЗДИЕ -%d": "⚔ RETRIBUTION -%d",
"⚔ ВОЗМЕЗДИЕ!": "RETRIBUTION!",
"⚔ Печать Возмездия карает %s на %d урона!": "⚔ The Seal of Retribution punishes %s for %d damage!",
"⚔️ Демонстрационный бой [%s]: %s!": "⚔️ Demonstration battle [%s]: %s!",
"⚔️ Остаться в бою": "⚔️ Stay in battle",
"⚠️ Отряд %s уже выжидал в этом раунде и обязан действовать!": "⚠️ Stack %s has already waited this round and must act!",
"⚠️ Отряд %s уже ждал в этом раунде и обязан действовать!": "⚠️ Stack %s has already waited this round and must act!",
"🏅 Без потерь! Безупречная тактическая победа!": "",
"• Без потерь! Безупречная тактическая победа!\n": "• No losses! A flawless tactical victory!\n",
"• %s: потеряно %d\n": "• %s: lost %d\n",
"✦ %s: ОБМЕН ✦": "✦ %s: SWAP ✦",
"✨ %s ослеплен и пропускает ход!": "✨ %s is blinded and skips the turn!",
"✨ ВДОХНОВЕНИЕ!": "INSPIRATION!",
"✨ С отряда %s сняты тёмные чары, боевой дух удвоен на 3 раунда!": "✨ Dark curses lifted from %s; morale doubled for 3 rounds!",
"🌟 [БОЕВОЙ ДУХ]: Воодушевленный отряд %s получает дополнительный ход!": "🌟 [HIGH MORALE]: The inspired stack %s gains an extra turn!",
"🌟 БОЕВОЙ ДУХ! (+1 ХОД)": "🌟 HIGH MORALE! (+1 TURN)",
"🌿 КОРНИ (0 ХОДОВ)": "🌿 ROOTED (0 MOVEMENT)",
"🌿 Корни древня оплетают %s, лишая возможности двигаться на 1 раунд!": "🌿 The treant's roots entangle %s, robbing it of movement for 1 round!",
"🍀 [УДАЧА]: Отряд %s наносит удвоенный сокрушительный урон!": "🍀 [LUCK]: The stack %s deals double crushing damage!",
"🍀 [УДАЧА]: Отряд %s совершает выстрел с удвоенным критическим уроном!": "🍀 [LUCK]: The stack %s fires a shot with double critical damage!",
"🍀 УДАЧА! (х2)": "🍀 LUCK! (x2)",
"🍀 Удача: 15% шанс двойного урона у вашего войска. 🌟 Боевой дух даёт доп. ход (Лидерство).": "🍀 Luck: your army has a 15% chance of double damage. 🌟 High Morale grants extra turns (Leadership).",
"🎯 Прямой выстрел! %s поражает %s на %d урона! (Потери: %d)": "🎯 Direct hit! %s strikes %s for %d damage! (Losses: %d)",
"🏳️ Да, отступить": "🏳️ Yes, retreat",
"🏳️ Отступить": "🏳️ Retreat",
"🏹 [ПРЯМОЙ ВЫСТРЕЛ: Дистанция %d]: Урон %d-%d (Потери: %d-%d)": "🏹 [DIRECT SHOT: Distance %d]: Damage %d-%d (Losses: %d-%d)",
"🏹 Второй выстрел! %s наносит %d урона по %s! (Потери: %d)": "🏹 Second shot! %s deals %d damage to %s! (Losses: %d)",
"☠ %s читает заклинание тёмного пламени...": "☠ %s begins chanting the dark flame...",
"☠ ТЬМА -%d": "☠ DARKNESS -%d",
"☠ Тёмное пламя %s поражает %s на %d урона! (Потери: %d)": "☠ %s's dark flame strikes %s for %d damage! (Losses: %d)",
"☣ БОЛЕЗНЬ! (-25% АТАКИ)": "☣ DISEASE! (-25% ATTACK)",
"☣ Трупный яд заражает %s: атака снижена на 25%% на 2 раунда!": "☣ Corpse poison infects %s: attack reduced by 25%% for 2 rounds!",
"💯": "",
"🛑 Стоп": "🛑 Stop",
"🛡 %s окружен куполом света: поглощает %d ед. урона в течение 3 раундов!": "🛡 %s is wrapped in a dome of light: absorbs %d damage for 3 rounds!",
"🛡 ЩИТ -%d": "🛡 SHIELD -%d",
"🛡 ЩИТ СВЕТА!": "SHIELD OF LIGHT!",
"🛡️ Защита": "🛡️ Defend",
"🛡️ Защита: %d (-%d%% урон)%s": "🛡️ Defense: %d (-%d%% damage)%s",
"🪞 %s отражает %d урона по %s!": "🪞 %s reflects %d damage back at %s!",
"🪞 ОТРАЖЕНИЕ -%d": "🪞 REFLECTED -%d",
"⚔️ Атака: %d (+%d%% урон)%s": "⚔️ Attack: %d (+%d%% damage)%s",
"⏩ Ускорение боя: %s": "⏩ Battle speed: %s",
"⏳ Ждал": "⏳ Waited",
"⏳ Ждать": "⏳ Wait",
"⏳ Отряд выжидает удобного момента...": "⏳ The stack bides its time...",
"💤 ОСЛЕПЛЕН": "💤 BLINDED",
"💨 %s ловко уклоняется: урон вдвое меньше!": "💨 %s nimbly dodges: damage halved!",
"💨 УКЛОНЕНИЕ!": "EVADED!",
"🔊 ВКЛЮЧЕНО (x2)": "ON (x2)",
"ВКЛЮЧЕНО (x2)": "ON (x2)",
"выключено": "off",
"🔥 [ОГНЕННОЕ ДЫХАНИЕ]: Струя пламени пробивает строй и поражает %s на %d урона! (Потери: %d)": "🔥 [FIRE BREATH]: A jet of flame pierces the line and hits %s for %d damage! (Losses: %d)",
"Ход отряда: %s (%d воинов). [W - Ждать%s, D - Защита, A - Авто, B - Магия]": "Stack's turn: %s (%d warriors). [W - Wait%s, D - Defend, A - Auto, B - Spells]",
"Мана: %d / %d": "Mana: %d / %d",
"Выберите цель для заклинания: %s (ПКМ/Esc для отмены)": "Choose a target for the spell: %s (RMB/Esc to cancel)",
"Не хватает маны на заклинание %s!": "Not enough mana for the spell %s!",
"Недостаточно маны для сотворения заклинания!": "Not enough mana to cast the spell!",
"Сотворение заклинания отменено.": "Spell casting cancelled.",
"🏆 Тренировочный поединок на Арене успешно завершен!\nСложность: %s\nПротивник: %s\n\nВы продемонстрировали выдающееся тактическое мастерство!": "The training duel in the Arena is complete!\nDifficulty: %s\nOpponent: %s\n\nYou have demonstrated outstanding tactical mastery!",
"Враг останется на своей позиции,\nи вы сможете атаковать его снова.\nПобеда пока не одержана.": "The enemy will hold its position,\nand you can attack it again.\nVictory has not yet been won.",
"Отступить из боя?": "Retreat from battle?",
"Вы рассеяли вражеский отряд!\n\nПолучено награды:\nЗолото: +%d\nОпыт героя: +%d": "You have scattered the enemy stack!\n\nRewards received:\nGold: +%d\nHero experience: +%d",
}
