# -*- coding: utf-8 -*-
# Переводы, батч 5: остатки из отчёта _missing_translations.txt.
T = {
"Авангард Разбойников": "The Bandit Vanguard",
"Аларик сокрушает %s Огненным Шаром! Урон: %d (Потери: %d)": "Alaric crushes %s with a Fireball! Damage: %d (Losses: %d)",
"Атака (+1)": "Attack (+1)",
"Защита (+1)": "Defense (+1)",
"Сила Магии (+1)": "Spell Power (+1)",
"Знание (+1)": "Knowledge (+1)",
"Атаман Разбойников": "The Bandit Chieftain",
"Благодарю вас!": "Our thanks!",
"Благодарю!": "Thank you!",
"Благословленные королевой лучницы. Стреляют дважды за один выстрел!": "Blessed archers of the queen. They fire twice with every shot!",
"Болотная Нежить": "The Swamp Undead",
"Болотная нежить": "Swamp undead",
"Болотный дозор": "The Fen Pickets",
"Бронзовые створки распахнуты. Дорога на Пик Дракона свободна!": "The bronze doors swing open. The road to Dragon Peak is clear!",
"Быстрый и свирепый хищник, способный молниеносно настигать стрелков.": "A swift and fierce predator that can run down shooters in a flash.",
"Вековой защитник чащи. Регенерирует 20 HP в раунд и может опутать врага корнями!": "An age-old warden of the wildwood. Regenerates 20 HP per round and can entangle foes with roots!",
"Великий магический взор пронзает пелену тумана! Окрестные земли и тайные тропы открыты вашему взору!": "A mighty magical gaze pierces the veil of fog! The surrounding lands and hidden paths lie open before you!",
"Верховный друид предлагает помощь природы:\n\nДоступно: %d лесных друидов (по %d золота)\nКазна: %d золота": "The Archdruid offers nature's aid:\n\nAvailable: %d forest druids (at %d gold each)\nTreasury: %d gold",
"Во славу Королевства!": "For the glory of the Kingdom!",
"Воины": "Warriors",
"Войско Героя": "Hero's Army",
"Волшебный фонтан освещает поляну мягким лазурным сиянием.\n\nГерой восполняет всю ману и ощущает прилив колдовских сил (+1 к Силе Магии)!": "A magical fountain bathes the glade in a soft azure glow.\n\nThe hero's mana is fully restored, and a surge of sorcerous power courses through him (+1 Spell Power)!",
"Восставшие стрелки из древних курганов. Не ведают страха и усталости.": "Risen archers of the ancient barrows. They know neither fear nor weariness.",
"Вперед": "Forward",
"Да будет так!": "So be it!",
"Дозор Стрелков": "The Archers' Pickets",
"Древни регенерируют каждый раунд — затягивайте бой на их стороне невыгодно.": "Treants regenerate every round — dragging out a fight against them is unwise.",
"Драконье дыхание пробивает строй на 2 гекса — не выстраивайтесь в линию!": "Dragon breath pierces 2 hexes through a line — never stand single-file!",
"Древние письмена потускнели. Обелиск уже даровал вам свою благодать.": "The ancient script has dimmed. The Obelisk has already bestowed its blessing on you.",
"Железные Врата Ущелья": "The Iron Gates of the Gorge",
"ЗАМЕДЛЕНИЕ!": "SLOWED!",
"Завершить кампанию": "Complete the campaign",
"Заклинание героя действует один раз за раунд — но не тратит ход отряда!": "The hero's spell acts once per round — and costs no stack its turn!",
"Закрыть": "Close",
"Засада Разбойников": "The Bandit Ambush",
"Зловещий склеп": "",
"Знание (+1) — мана восполнена!": "Knowledge (+1) — mana restored!",
"Золото: +%d\nОпыт героя: +%d": "Gold: +%d\nHero experience: +%d",
"Звуки:": "Sound:",
"Игра сохранена!": "Game saved!",
"Исцеление: %s восстанавливает %d ед. здоровья!": "Heal: %s restores %d health!",
"Кабы не было оси, так бы бык убежал": "",
"Клетка с феями опустела. Духи леса благодарят вас!": "",
"Ключ от Врат": "The Gate Key",
"Костяной Ключ": "The Bone Key",
"Кузнецы Владык перековали ваше войско!": "",
"Лесные духи на службе Королевства!": "",
"Мана: %d / %d 🔮": "Mana: %d / %d 🔮",
"Мана полностью восстановлена!": "",
"Мастер тайной магии.\n\n• Атака: 2  |  Защита: 2\n• Магия: 6  |  Знание: 6 (80 MP)\n• Навык: Волшебство (+25% урон чар)\n• Войско: 4 Грифона, 24 Феи\n• Предмет: Перстень Архимага": "A master of secret magic.\n\n• Attack: 2  |  Defense: 2\n• Power: 6  |  Knowledge: 6 (80 MP)\n• Skill: Sorcery (+25% spell damage)\n• Army: 4 Griffins, 24 Fairies\n• Item: Archmage's Ring",
"Мгновенно разрешить исход боя (риск потерь)": "",
"Нанять: %s (%d зол.)": "",
"Не хватает золота: нужно %d зол.": "",
"ОБМЕН МЕСТАМИ": "",
"Огненный Дозор": "The Fire Watch",
"Око Орла (10 маны)": "",
"Опыт героя: +%d": "Hero experience: +%d",
"Отряд фей-лучниц пополняет ваши ряды!": "",
"Перевал Дракона": "The Dragon's Pass",
"Перстень Архимага в рюкзаке!": "",
"Печать: %s": "",
"Повысить точность?": "",
"Поговорить": "Talk",
"Покинуть логово": "",
"Получен артефакт: %s!": "",
"Получены сокровища: %d золота!": "",
"Помощь Лесника": "",
"Продолжить победное шествие!": "",
"Разбойники повержены, и сокровища ваши!": "",
"Свернуть лагерь": "",
"Слоты сохранений:": "Save slots:",
"Сокровищница Обелиска": "",
"Стража пала — сокровища ваши!": "",
"Сunchecked": "",
"Тактическая арена": "Tactical Arena",
"Тьма (50+ врагов)": "Darkness (50+ enemies)",
"Ускорение боя": "Battle speed",
"Хижина Лесника": "The Forester's Hut",
"Ход: %d / %d": "Movement: %d / %d",
"Хранитель маяка": "",
"Шайка гоблинов-грабителей": "The Goblin Raiders",
"Шайка разбойников": "The Bandit Gang",
"медленно и безопасно": "",
"быстро, но с потерями": "",
"Алтарь Друидов": "The Druid Altar",
"Быстрый бой: %s": "Quick battle: %s",
"В бой!": "To battle!",
"Выбрать другой отряд": "",
"Забрать Венец Королевы Фей": "",
"Кузница": "The Forge",
"Мана героя: %d / %d": "Hero mana: %d / %d",
"Не хватает маны: нужно %d 🔮": "",
"Осмотреть реликвии": "",
"Первая глава завершена!": "",
"Проклятые Топи": "The Cursed Fens",
"Ускорение боя (x2)": "",
"делится золотом": "",
"МУЗЫКАЛЬНАЯ ШКАТУЛКА": "",
"Свиток: %s": "",
"ОК": "OK",
}
